// Animation instances and sprite-derived data of Classic dc16.exe (animate.c), ported bit-exactly
// as far as the simulation depends on them. Pixel data, frame-part overlays (muzzle flashes,
// smoke), cell draw flags and everything else that only reaches the screen is NOT here.
//
// PORT NOTES
// ==========
//
// Data source: data/classic/sprites.json, generated by tools/sprdata2json.js from ANIM.DAT,
// ANIMATE/*.FIN, SPRITES/*.SPR and GAMESTAT/{GAMESTAT,WEAPSTAT,BOOMSTAT}.TXT. Load it once with
// `G.sprites = loadSprites(JSON.parse(...))`; every function here reads `G.sprites`.
//
// Formats (animate.c 0x4255FC, start-up reader 0x4051CC), see the header of tools/sprdata2json.js:
//   ANIM.DAT       one FIN name per line, loaded in order into registry level 0 (banks 0x4D619C,
//                  animations 0x4D61A8; hash tables keyed by exact, case-sensitive name). Interface
//                  screens push a level (0x426740 loads the FINs named in intrface/*.dat, searched
//                  before level 0), but none of those FINs (knobe, choa, mwin, net, netd, sera, acom,
//                  chaa, mish, misa, mise, acar, hcar, enca, vcal, vcea, serg, dcuk, dcut, dcss)
//                  defines a name the balance loaders look up, so resolution is ANIM.DAT-only.
//                  The 71 ANIMATE/*.FIN files not listed in ANIM.DAT nor in a DAT (TMP, FILL, PUST,
//                  EFFECTS, NAPALM, ...) are never loaded, although some define colliding names.
//   FIN            u16 0x1D, u16 nframes, u16 nanims, u16 nbanks; nbanks x char[8] bank; nanims x
//                  { char[16] name, u16 first, u16 last }; nframes x { u16 ncells, u16 duration,
//                  8 x { char[16] part animation, i16 x, i16 y } }; sum(ncells) x { char[8] bank,
//                  u16 cell, i16 x, i16 y, 4 x u16 display flags }.
//   duration       file value 0 -> 15; ticks = trunc(15 * (value + 3) / 100), stored as int16.
//   frame parts    8 named sub-animation slots per frame; NONAME or an unknown name = empty.
//                  Slot 7 = muzzle hotspot (0x426338), slot 6 = "aim point" (0x426304), the rest
//                  are drawn overlays (display only).
//
// Name -> animation set (0x426014): "<base><suffix><n>" for the 16 file facings n = (12 - i) & 15,
// expanded to 32 game facings; facing f uses file index f >> 1, missing ones take the nearest
// existing facing in the probe order 0, +1, -1, +2, -2, ... (table 0x489628). Sets are allocated
// per call of 0x426540 (one 160-byte record each, max 1000, pool reset per game at 0x43C44C) and
// compared BY IDENTITY in startAnim, so the JSON gives every allocation its own id in the original
// allocation order: BOOMSTAT sets, then per object type MOVE (mobile only), STAND, FIRE/FIREA/
// FIREB/FIREC, DIE or DIEA/DIEB/DIEC, DEPLOY, FUNK, FIG, BUILDSTAND/BUILD, SCRCH, BURN,
// BLOODA..BLOODG, then per weapon BULLET, EXPLODE/EXPL. Set id 0 = NULL. Fallbacks share ids
// exactly like the original shares pointers (DEPLOY/FUNK/FIG/DIE -> STAND, BURN -> SCRCH -> STAND).
// Animation ids are compact indices of the animations reachable from a set (identity of an
// animation is never compared by the engine).
//
// Object-type sprite fields (GAMESTAT loader 0x43BB80, 0x43BA3C, 0x43BB30):
//   +0x7C MOVE (only if speed != 0)   +0x80 STAND (asserted to exist)   +0x84 SCRCH   +0x88 BURN
//   +0x8C FIG   +0x94 DEPLOY   +0x98 BUILDSTAND else BUILD else NULL   +0x9C FUNK
//   +0xA0..+0xA8 FIRE[3] + count +0xE4:  "<name>FIRE0" -> FIRE; "<name>FIREA0" -> FIREA (replaces
//        slot 0); FIREB0 / FIREC0 append; none -> STAND, count 1. Only facing 0 is probed here.
//   +0xAC..+0xB4 DIE[3] + count +0xE8:  any even "<name>DIE<n>" -> [DIE]; else DIEA, then DIEB, then
//        DIEC while the previous one exists; none -> [STAND].
//   +0xBC.. BLOOD[7] + count +0xD8:  BLOODA..BLOODG, gaps skipped.
//   +0x48..+0x57 bounding box {x0, z0, x1, z1}: 0x425FB4 over the 32 STAND facings of every frame
//        and cell: per cell {xoff + x, -y, xoff + x + w, h - y} (pixels, then normalised and << 3).
//        The union 0x4364AC is min/min/LAST/max - its x1 is the last cell's x1 (`cmp eax,eax`
//        compiler artefact), reproduced. Non-flyers (+0x60 == 0) are widened to at least +-96.
//   +0x58/+0x5C "aim point" = frame part 6 of STAND[facing 0]'s first frame as (x, -y), else
//        (0, -(z1 >> 3)) from the unwidened box. No reader of these two fields was found in the
//        simulation code (0x412000-0x446000); kept as `aim` for completeness.
// Weapons (0x43B6EC): +0x2C BULLET set if "<name>BULLET0" exists; +0x30.. EXPLODE (or EXPL) set,
//   count +0x40 = 1; when the blast type (+0x1C) > 0 the boom's sets (up to 4) REPLACE them.
// Booms (0x43B424): each name line until NONE (max 4) is one set whose 32 facings all hold the
//   animation of that exact name (NULL facings if it does not exist - none in Classic).
//
// Animation instance = 8-byte slot (objects: O.ANIM0/1/2; missiles: MS.ANIM):
//   +0 int32 set id (pointer in the original; 0 = NULL)   +4 u8 frame   +5 u8 delay
//   +6 u8 status/mode: 0 loop, 1 play once (-> 2), 2 finished, 3 play once and hold last frame
//   +7 unused.  O.ANIM*_STATUS = slot + 6; the missile status byte is MS.ANIM + SLOT_STATUS (0x26).
// startAnim(slot, set, mode) 0x42626C: no-op when the slot already holds this set with this mode
//   (so restarting STAND/loop keeps the frame), else frame = delay = 0, status = mode.
// advance(slot, facing) 0x426428, once per tick: status 2 -> nothing. If delay == 0: frame++.
//   If frame >= count: frame = 0; mode 1 -> status 2 (finished), mode 3 -> frame = count-1 and
//   return; otherwise (loop) continue with frame 0. Whenever the frame changed, delay = duration
//   of the new frame. Then delay--. Consequence: after startAnim the first frame is left at the
//   first advance (delay starts at 0), so a play-once animation with durations d[0..n-1] finishes
//   (status 2) on tick 1 + d[1] + ... + d[n-1] after it was started; a 1-frame animation on tick 1.
// running(slot, facing) 0x426294: 0 when finished (status 2, or frame past the end in mode 1 which
//   sets status 2); otherwise 1, resetting frame/delay at the end for loop/hold modes.
// Facing: objects use ((((heading + 8) & 0xFF) >> 4) << 4) >> 3 (even 0..30, dispatcher 0x41952D
//   and fire_weapon 0x413172), missiles use MS.FACING >> 3 (0..31, 0x442BA3).
// Dispatcher 0x4194DC step 3 (advanceAnims): if the blood slot (ANIM1) is not running and
//   O.DAMAGED != 0: when the type has blood sets, start blood[rand() % count] once (rand() consumed
//   only then); O.DAMAGED = 0 in either case. Then advance ANIM0, ANIM1, ANIM2 with the facing.
//   initObject 0x41B124 starts STAND in ANIM0 with mode 0 and in ANIM1/ANIM2 with mode 2.
// Hotspots 0x426338(slotptr, facing, &count, out, part = 7): for every frame of set[facing], if
//   part 7 is set: (x * 8, -y * 8, ticks of the frames before it); assert count < 8. Classic data
//   never has more than one per animation. fire_weapon substitutes one (0, 0, 0) when there are
//   none (0x41319B) and create_missile stores delay << 2 in MS.DELAY (0x441A66).
// Bounding-box test 0x43658C(x0, z0, x1, z1, px, pz): x0 <= px < x1 && z0 <= pz < z1.
//
// rand() call sites in this module: advanceAnims (the blood overlay, 0x41966E).
// Nothing left as TODO(exact).
//
// Disagreements with docs/DC16_BATTLE_ENGINE.md (the code wins):
//   * section 6 step 4 says "up to 7 muzzle hotspots ... delay x 4": the reader allows 8 (assert
//     `offset_pos < MAX_PROBED_OFFSETS`), Classic data has at most 1, and the x4 is applied by
//     create_missile, not by the hotspot reader.
//   * section 4.2 step 3 says "if +0xC7 is set and the type has blood sprites, start a random BLOOD
//     overlay": only when the blood slot is not running; the flag is then cleared even without
//     blood sprites; rand() is only consumed when the type has blood sets.
//   * section 2.1 says explosion sprites are "<name>EXPLODE / EXPL, otherwise the blast type's":
//     when the blast type has sets they replace the weapon's own; the own set is only used when the
//     blast type is 0 or has no sets.
//   * section 2.2 lists +0x48..+0x57 as the bounding box but not the x1 quirk, the 32-facing/all-
//     frames extent, nor the +0x58/+0x5C aim point.
//   * section 15.2 "production time is the length of the unit's BUILD animation": it is
//     1 + sum of the durations of frames 1..n-1 ticks (the first frame's own duration is skipped).

import { O, u8, w8, i32, w32, objAddr, irem } from './mem.js';

export const FORMAT = 'dc16-sprites';

/** Slot layout (8 bytes). */
export const SLOT_SET = 0;
export const SLOT_FRAME = 4;
export const SLOT_DELAY = 5;
export const SLOT_STATUS = 6;

/** startAnim modes / status values. */
export const MODE_LOOP = 0;
export const MODE_ONCE = 1;
export const MODE_DONE = 2; // "already finished" (initObject uses it for the two overlay slots)
export const MODE_HOLD = 3;
export const STATUS_FINISHED = 2;

export const NULL_SET = 0;
export const HOTSPOT_PART = 7;
export const MAX_HOTSPOTS = 8;

/** Pose names accepted by pose(): the object-type sprite fields. */
export const POSES = Object.freeze({
  MOVE: 'move', STAND: 'stand', SCRCH: 'scrch', BURN: 'burn', FIG: 'fig', DEPLOY: 'deploy', BUILD: 'build', FUNK: 'funk',
  FIRE: 'fire', DIE: 'die', BLOOD: 'blood',
});

// ---- loading -------------------------------------------------------------------------------------

/**
 * Turn data/classic/sprites.json into the run-time tables. Returns
 * { anims: [{ name, count, dur: int[], hot: [{x, z, delay}] }], sets: [null | { name, anims: int[32] }],
 *   types: [{ name, fly, bbox, aim, move, stand, ..., fire[], die[], blood[] }], weapons: [null | { bullet, explode[] }],
 *   booms: [{ size, sets[] }] }.
 */
export function loadSprites(json) {
  if (!json || json.format !== FORMAT) throw new Error(`sprites.json: expected format ${FORMAT}`);
  const anims = json.anims.map((a) => Object.freeze({
    name: a.n,
    count: a.d.length,
    dur: Object.freeze(a.d.slice()),
    hot: Object.freeze((a.h ?? []).map(([x, z, delay]) => Object.freeze({ x, z, delay }))),
  }));
  const sets = json.sets.map((s) => (s ? Object.freeze({ name: s.n, anims: Object.freeze(s.a.slice()) }) : null));
  const types = json.types.map((t) => Object.freeze({
    name: t.name, fly: t.fly, bbox: Object.freeze(t.bbox.slice()), aim: Object.freeze(t.aim.slice()),
    move: t.move, stand: t.stand, scrch: t.scrch, burn: t.burn, fig: t.fig, deploy: t.deploy, build: t.build, funk: t.funk,
    fire: Object.freeze(t.fire.slice()), die: Object.freeze(t.die.slice()), blood: Object.freeze(t.blood.slice()),
  }));
  const weapons = json.weapons.map((w) => (w ? Object.freeze({ name: w.name, bullet: w.bullet, explode: Object.freeze(w.explode.slice()) }) : null));
  const booms = json.booms.map((b) => (b ? Object.freeze({ size: b.size, sets: Object.freeze(b.sets.slice()) }) : null));
  return Object.freeze({ anims, sets, types, weapons, booms });
}

function sprites(G) {
  const s = G.sprites;
  if (!s) throw new Error('G.sprites is not loaded (Anim.loadSprites)');
  return s;
}

// ---- lookups -------------------------------------------------------------------------------------

/** The animation record of set `setId` at game facing 0..31 (set[facing] in the original). */
export function animOf(G, setId, facing) {
  const set = sprites(G).sets[setId];
  if (!set) throw new Error(`animation set ${setId} is NULL`); // the original would dereference NULL
  const a = sprites(G).anims[set.anims[facing]];
  if (!a) throw new Error(`set ${set.name} has no animation at facing ${facing}`);
  return a;
}

export const typeSprites = (G, type) => sprites(G).types[type];
export const weaponSprites = (G, weapon) => sprites(G).weapons[weapon];
export const boomSprites = (G, boom) => sprites(G).booms[boom];

/**
 * Set id of a pose of an object type: pose(G, type, 'STAND'), pose(G, type, 'FIRE', k), ...
 * Returns NULL_SET (0) where the original holds a NULL pointer (MOVE of immobile types, missing BUILD).
 */
export function pose(G, type, name, k = 0) {
  const t = typeSprites(G, type);
  const field = POSES[name];
  if (!field) throw new Error(`unknown pose ${name}`);
  const v = t[field];
  if (Array.isArray(v)) return v[k] ?? NULL_SET;
  return v;
}

export const fireCount = (G, type) => typeSprites(G, type).fire.length; // type +0xE4
export const dieCount = (G, type) => typeSprites(G, type).die.length; // type +0xE8
export const bloodCount = (G, type) => typeSprites(G, type).blood.length; // type +0xD8

/** Number of frames of set[facing] (anim header +0x28). */
export const frameCount = (G, setId, facing) => animOf(G, setId, facing).count;

/** Object facing index used by the dispatcher (0x41952D) and fire_weapon (0x413172): even 0..30. */
export const objFacing = (heading) => ((((heading + 8) & 0xff) >> 4) << 4) >> 3;

/** Missile facing index (0x442BA3): MS.FACING (0..255) >> 3. */
export const missileFacing = (facing) => facing >> 3;

// ---- the slot primitives ---------------------------------------------------------------------------

/** startAnim 0x42626C(slot, set, mode). */
export function startAnim(G, slot, setId, mode) {
  const gs = G.gs;
  if (i32(gs, slot + SLOT_SET) === setId && u8(gs, slot + SLOT_STATUS) === (mode & 0xff)) return;
  w8(gs, slot + SLOT_FRAME, 0);
  w8(gs, slot + SLOT_DELAY, 0);
  w8(gs, slot + SLOT_STATUS, mode);
  w32(gs, slot + SLOT_SET, setId);
}

/** anim_running 0x426294(slot, facing) -> 0 when finished, else 1 (with the end-of-loop reset). */
export function running(G, slot, facing) {
  const gs = G.gs;
  const anim = animOf(G, i32(gs, slot + SLOT_SET), facing);
  if (u8(gs, slot + SLOT_STATUS) === STATUS_FINISHED) return 0;
  let load = false;
  if (u8(gs, slot + SLOT_FRAME) >= anim.count) {
    const status = u8(gs, slot + SLOT_STATUS);
    w8(gs, slot + SLOT_FRAME, 0);
    load = true;
    if (status === MODE_ONCE) {
      w8(gs, slot + SLOT_STATUS, STATUS_FINISHED);
      return 0;
    }
    if (status === MODE_HOLD) {
      w8(gs, slot + SLOT_FRAME, anim.count - 1);
      return 1;
    }
  }
  if (load) w8(gs, slot + SLOT_DELAY, anim.dur[u8(gs, slot + SLOT_FRAME)]);
  return 1;
}

/** advance 0x426428(slot, facing): one tick of the animation. */
export function advance(G, slot, facing) {
  const gs = G.gs;
  const anim = animOf(G, i32(gs, slot + SLOT_SET), facing);
  if (u8(gs, slot + SLOT_STATUS) === STATUS_FINISHED) return;
  let load = false;
  if (u8(gs, slot + SLOT_DELAY) === 0) {
    load = true;
    w8(gs, slot + SLOT_FRAME, u8(gs, slot + SLOT_FRAME) + 1);
  }
  if (anim.count <= u8(gs, slot + SLOT_FRAME)) {
    load = true;
    const status = u8(gs, slot + SLOT_STATUS);
    w8(gs, slot + SLOT_FRAME, 0);
    if (status === MODE_ONCE) {
      w8(gs, slot + SLOT_STATUS, STATUS_FINISHED);
      return;
    }
    if (status === MODE_HOLD) {
      w8(gs, slot + SLOT_FRAME, anim.count - 1);
      return;
    }
  }
  if (load) w8(gs, slot + SLOT_DELAY, anim.dur[u8(gs, slot + SLOT_FRAME)]);
  w8(gs, slot + SLOT_DELAY, u8(gs, slot + SLOT_DELAY) - 1);
}

export const status = (G, slot) => u8(G.gs, slot + SLOT_STATUS);
export const isFinished = (G, slot) => u8(G.gs, slot + SLOT_STATUS) === STATUS_FINISHED;
export const slotSet = (G, slot) => i32(G.gs, slot + SLOT_SET);
export const slotFrame = (G, slot) => u8(G.gs, slot + SLOT_FRAME);

/**
 * Dispatcher 0x4194DC step 3 (0x41964B..0x4196C4): blood overlay and the per-tick advance of the
 * three slots of object `obj`. Uses the heading as it is when called (the dispatcher computes the
 * facing at entry; steps 1-2 do not change the heading).
 */
export function advanceAnims(G, obj) {
  const gs = G.gs;
  const a = objAddr(obj);
  const facing = objFacing(u8(gs, a + O.HEADING));
  if (!running(G, a + O.ANIM1, facing)) {
    if (u8(gs, a + O.DAMAGED) !== 0) {
      const blood = typeSprites(G, u8(gs, a + O.TYPE)).blood;
      if (blood.length > 0) {
        const k = irem(G.rand(), blood.length); // rand() consumed for the blood overlay (0x41966E)
        startAnim(G, a + O.ANIM1, blood[k], MODE_ONCE);
      }
      w8(gs, a + O.DAMAGED, 0);
    }
  }
  advance(G, a + O.ANIM0, facing);
  advance(G, a + O.ANIM1, facing);
  advance(G, a + O.ANIM2, facing);
}

// ---- sprite-derived geometry -----------------------------------------------------------------------

/**
 * Hotspot reader 0x426338(slot, facing, ..., part 7): the muzzle points of the slot's current set at
 * `facing`, in order, as { x, z, delay } (position units, ticks). Empty when the animation has none.
 */
export function hotspots(G, slot, facing) {
  return hotspotsOfSet(G, i32(G.gs, slot + SLOT_SET), facing);
}

export function hotspotsOfSet(G, setId, facing) {
  return animOf(G, setId, facing).hot;
}

/** fire_weapon's use (0x41318F..0x4131A9): the hotspots, or one dummy (0, 0, 0) when there are none. */
export function fireHotspots(G, slot, facing) {
  const h = hotspots(G, slot, facing);
  return h.length > 0 ? h : DUMMY_HOTSPOT;
}
const DUMMY_HOTSPOT = Object.freeze([Object.freeze({ x: 0, z: 0, delay: 0 })]);

/** Object-type bounding box +0x48..+0x57 as [x0, z0, x1, z1] (position units, widened for non-flyers). */
export const bbox = (G, type) => typeSprites(G, type).bbox;

/** Object-type aim point +0x58/+0x5C as [x, z] (see PORT NOTES; no simulation reader found). */
export const aimPoint = (G, type) => typeSprites(G, type).aim;

/** 0x43658C(x0, z0, x1, z1, px, pz): half-open rectangle test. */
export const pointInBox = (box, px, pz) => (px >= box[0] && px < box[2] && pz >= box[1] && pz < box[3] ? 1 : 0);

/** Resolve a set by the name the loader gave it ("TRSCSTAND", "BARRBULLET", "NUKE"); first allocation wins. */
export function resolveSprite(G, name) {
  const sets = sprites(G).sets;
  for (let i = 1; i < sets.length; i++) if (sets[i].name === name) return i;
  return NULL_SET;
}

// ---- integration aliases (11 Sep 2026) ------------------------------------------------------------

/** anim_running 0x426294 as a boolean (ticker.js name). */
export const isPlaying = (G, slot, facing) => running(G, slot, facing) !== 0;
/** The set id of a slot (dword at +0; ticker.js name). */
export const currentAnim = slotSet;

/**
 * Only the three 0x426428 advances of the dispatcher (0x4196A6..0x4196C4); the blood-overlay start
 * that precedes them in the original is done by the caller (ticker.js dispatchObject).
 */
export function advanceSlots(G, obj, facing) {
  const a = objAddr(obj);
  advance(G, a + O.ANIM0, facing);
  advance(G, a + O.ANIM1, facing);
  advance(G, a + O.ANIM2, facing);
}
