#!/usr/bin/env python3
"""Is the integrity manifest embedded in Apply-DarkColonyPatches.ps1 in step with the game repository?

The patcher (generated by gen_apply_script.py) carries a manifest of every file the repository ships -
path, size, SHA-256 - and refuses to patch a folder whose files differ from it (1 Oct 2026, display doc
10.60).  So the patcher must be REGENERATED after any commit that changes a shipped game file, or every
fresh clone fails the check.  This tool compares the manifest of a patcher script with the repository's
index (what a clone or the GitHub ZIP delivers) and lists every difference.

    python check_manifest.py <Dark-Colony repo>            (its Apply-DarkColonyPatches.ps1)
    python check_manifest.py <Dark-Colony repo> <script>   (another copy of the script)

Exit code 0 = in step, 1 = stale (regenerate: python gen_apply_script.py <repo> <repo>/Apply-DarkColonyPatches.ps1).
Stdlib only.
"""
import hashlib, os, re, subprocess, sys

TOOLS = os.path.dirname(os.path.abspath(__file__))


def script_manifest(path):
    text = open(path, 'rb').read().decode('utf-8', 'replace')
    m = re.search(r"^\$ManifestText = @'\r?\n(.*?)\r?\n'@", text, re.S | re.M)
    if not m:
        sys.exit('no $ManifestText in ' + path)
    out = {}
    for line in m.group(1).splitlines():
        line = line.strip()
        if not line:
            continue
        kind, size, h, p = line.split(' ', 3)
        out[p] = (kind == 'T', int(size), h)
    return out


def repo_manifest(repo, excluded):
    """The same hashes from the repository's index (see gen_apply_script.manifest_entries)."""
    r = subprocess.run(['git', '-C', repo, 'ls-files', '-s', '-z'], capture_output=True, check=True)
    wanted = []
    for rec in r.stdout.split(b'\0'):
        if not rec:
            continue
        meta, p = rec.split(b'\t', 1)
        p = p.decode('utf-8')
        if not excluded(p):
            wanted.append((p, meta.split()[1].decode()))
    proc = subprocess.Popen(['git', '-C', repo, 'cat-file', '--batch'], stdin=subprocess.PIPE, stdout=subprocess.PIPE)
    out = {}
    for p, blob in wanted:
        proc.stdin.write((blob + '\n').encode()); proc.stdin.flush()
        hdr = proc.stdout.readline().split()
        size = int(hdr[2])
        data = proc.stdout.read(size); proc.stdout.read(1)
        text = b'\0' not in data
        if text:
            data = data.replace(b'\r', b'')
        out[p] = (text, len(data), hashlib.sha256(data).hexdigest()[:16])
    proc.stdin.close(); proc.wait()
    return out


def main(argv):
    if len(argv) < 2:
        sys.exit(__doc__)
    repo = argv[1]
    script = argv[2] if len(argv) > 2 else os.path.join(repo, 'Apply-DarkColonyPatches.ps1')
    # the generator's exclusion rule, imported without running the generator (it reads sys.argv at import)
    src = open(os.path.join(TOOLS, 'gen_apply_script.py'), encoding='utf-8').read()
    ns = {}
    block = re.search(r'^def manifest_excluded\(path\):.*?^    return False\n', src, re.S | re.M).group(0)
    builds = re.search(r'^BUILDS = \[.*?^\]\n', src, re.S | re.M).group(0)
    classic = re.search(r"^CLASSIC_DEPRECATED = \(.*?\)\n", src, re.S | re.M).group(0)
    maped = re.search(r'^MAPED_STEPS = \[.*?\]\n', src, re.S | re.M).group(0)
    exec('import os\n' + classic + maped + builds + "PATCHER_NAME = 'Apply-DarkColonyPatches.ps1'\n" + block, ns)
    have = script_manifest(script)
    want = repo_manifest(repo, ns['manifest_excluded'])
    stale = []
    for p in sorted(set(have) | set(want), key=str.lower):
        if p not in want:
            stale.append(('no longer in the repository', p))
        elif p not in have:
            stale.append(('new in the repository     ', p))
        elif have[p] != want[p]:
            stale.append(('changed                   ', p))
    print('manifest: {} files in the script, {} shipped by the repository'.format(len(have), len(want)))
    for why, p in stale:
        print('  {}  {}'.format(why, p))
    if stale:
        print('STALE: {} difference(s) - regenerate the patcher: python gen_apply_script.py "{}" "{}"'.format(len(stale), repo, os.path.join(repo, 'Apply-DarkColonyPatches.ps1')))
        return 1
    print('in step: every fresh clone passes the integrity check')
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
