// Dark Colony scenario ("map") files -> JSON. Library + CLI, no dependencies.
//
//   node tools/map2json.js <dir-or-.SCN> [...] [--out DIR] [--rooms] [--images] [--pretty]
//
//   node tools/map2json.js "../Dark-Colony/DC - Classic/SCENARIO/MPLAYER" --rooms --out maps
//       the seven maps of the server's default ROOMS (src/config.js) -> maps/<BASE>.json + maps/index.json
//   node tools/map2json.js "../Dark-Colony/DC - Classic/SCENARIO/MPLAYER" --out some/dir
//       every scenario of the folder (not kept in the repository; generate on request)
//   node tools/map2json.js "../Dark-Colony/DC - Classic/SCENARIO/MPLAYER/D8PLAY01.SCN"
//       one scenario -> stdout
//
// A scenario is a set of files sharing a base name: .SCN (text: names, day/night, teams, objects),
// .MAP (binary tile grid), .MTG (binary trigger-id grid), .PTH (binary path families and routing
// matrix), .TRO (text trigger script), .POP (text, map editor's vent eruption data, not read by
// the game) and the overview-image caches .OVH/.O16 (regenerated by the game, exported only with
// --images). The formats and the addresses of the game's loaders are documented in
// docs/DC16_MAP_FILES.md; that document is the reference for every field written here.
//
// Coordinates: the JSON uses the game's own tile coordinates (x, z). All grids are indexed
// [z][x] with z = 0 at the LAST row of the .MAP/.MTG file (the game flips those two files on
// load; .PTH, .SCN, .TRO and .POP are already in game order). Row r of the file is z = height-1-r.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { DEFAULTS } from '../src/config.js';

export const FORMAT = 'dc16-scenario';
export const FORMAT_VERSION = 1;

/** Object type names (GAMESTAT/GAMESTAT.TXT row order = type id; the file's own comments). */
export const TYPE_NAMES = [
  'TRSC Security trooper', 'TURR Turret tower', 'REAP Mech', 'BARR Thunderbolt mortar', 'SARG Cyborg',
  'SCGM Scout VTOL', 'EXPL Exploiter', 'ATRIL Carry-all', 'GRAY Grey warrior', 'XENO Grey elite',
  'SCYT Scyth demon', 'ATRIL Atril', 'PSYC Psy-raider', 'ORTU Saucer scout', 'SLUG Worker',
  'ATRIL Gray carry-all', 'EXCOPOD Exco center', 'BRRKPOD Barracks', 'ROBOPOD Robot factory 1',
  'ROBOPOD2 Robot factory 2', 'SCNCPOD Science pod 1', 'SCNCPOD2 Science pod 2', 'RSCHPOD Research pod',
  'SALY Salimander', 'AVII Batt', 'RNAT Renat (desert creature)', 'SPID Desert spider',
  'ATRIL Human escort', 'BIOHIV Mind hive', 'WARHIVE Warrior hive', 'BRDRHIV Breeder hive 1',
  'BRDRHIV2 Breeder hive 2', 'MINDHIV Alien science pod 1', 'MNDHIV2 Alien science pod 2',
  'RSCHIV Alien research pod 1', 'RSCHIV Alien research pod 2', 'GRUB Grub', 'POOP Artifact site',
  'RNAT Defense node 2', 'ATRIL Defense node 3', 'VENT Petra vent (lar)', 'T Human mobile tower',
  'XDEPLOY Alien mobile tower', 'ENGI Human mine layer', 'SLOM Alien mine layer', 'HMINE Human mine',
  'HMINE Alien mine', 'EDPLY Human mining tower', 'SDPL Alien mining tower', 'BEON Human healer',
  'ZISP Alien healer', 'ONEF Light', 'ONEF Light', 'ONEF Light', 'TWOF Light', 'TWOF Light', 'TWOF Light',
  'ONEF Light', 'ONEF Light', 'ONEF Light', 'TWOF Light', 'TWOF Light', 'TWOF Light', 'LENS Lens artifact',
  'MAKT Maktor artifact', 'LUNA Lunatek artifact', 'HYYK Pinball artifact', 'TEKT Tektarra artifact',
  'TOXX Ultimate artifact', 'TRSC Human lieutenant', 'TRSC Human captain', 'TRSC Human major',
  'TRSC Human colonel', 'GRAY Alien lieutenant', 'GRAY Alien captain', 'GRAY Alien major',
  'GRAY Alien colonel', 'SARGSTL Stealing cyborg', 'PSYCSTL Stealing psy-raider', 'GRND Ground drone',
  'AIRD Air drone', 'TOWR City centre tower', 'SALA Salad shooter', 'CRYO Cryo chamber', 'BEAC Drop beacon',
  'FUEL Fuel', 'DISH Com tower', 'FETU Fetus incubator', 'TORT Alien torture rack', 'CENT Dropship mind link',
  'FILL Psy-energy store', 'TONG Alien com tower', 'DROP Human drop ship', 'SAUC Alien drop ship',
  'DOTT Vision sight', 'BEEK Deactivated drop beacon', 'PCFO PC Format mag stack', 'WATC Alien eye',
  'CAM Camcorder', 'FUEL Fuel 500', 'FUEL Fuel 5000', 'FILL Psy-energy store 5000',
  'FILL Psy-energy store 10000', 'DROA Ground drone', 'SHRI Air drone', 'PORT Alien ultimate artifact',
];

export const TYPE_VENT = 40;
export const TYPE_ARTIFACT_SITE = 37;
export const MAX_TILE = 0x578; // MAXTILE, mapit.c asserts
export const MAX_MAP_SIDE = 256;
export const OVERVIEW = { width: 96, height: 84, planes: 2 };

// ---------------------------------------------------------------------------------------------
// Binary files

/** .MAP: u32 width, u32 height, width*height x {u16 background, u16 foreground}, width*height x u16 attributes. */
export function parseMap(buf) {
  if (buf.length < 8) throw new Error('.MAP too short');
  const width = buf.readUInt32LE(0);
  const height = buf.readUInt32LE(4);
  if (width < 1 || width > MAX_MAP_SIDE || height < 1 || height > MAX_MAP_SIDE) {
    throw new Error(`.MAP size ${width}x${height} out of range 1..256`);
  }
  const n = width * height;
  if (buf.length !== 8 + 6 * n) throw new Error(`.MAP length ${buf.length}, expected ${8 + 6 * n} for ${width}x${height}`);
  const background = [];
  const foreground = [];
  const attributes = [];
  for (let z = 0; z < height; z++) {
    const r = height - 1 - z; // file row -> game z
    const bg = new Array(width);
    const fg = new Array(width);
    const at = new Array(width);
    for (let x = 0; x < width; x++) {
      const i = r * width + x;
      bg[x] = buf.readUInt16LE(8 + i * 4);
      fg[x] = buf.readUInt16LE(8 + i * 4 + 2);
      at[x] = buf.readUInt16LE(8 + 4 * n + i * 2);
    }
    background.push(bg);
    foreground.push(fg);
    attributes.push(at);
  }
  return { width, height, background, foreground, attributes };
}

/** .MTG: u8 width, u8 height, width*height x u8 trigger id (bits 6 and 7 must be clear). */
export function parseMtg(buf, width, height) {
  if (buf.length !== 2 + width * height) throw new Error(`.MTG length ${buf.length}, expected ${2 + width * height}`);
  if (buf[0] !== (width & 0xff) || buf[1] !== (height & 0xff)) {
    throw new Error(`.MTG header ${buf[0]}x${buf[1]} does not match the .MAP ${width}x${height}`);
  }
  const grid = [];
  let maxTrigger = 0;
  for (let z = 0; z < height; z++) {
    const r = height - 1 - z;
    const row = new Array(width);
    for (let x = 0; x < width; x++) {
      const v = buf[2 + r * width + x];
      if (v & 0xc0) throw new Error(`.MTG trigger ${v} at x=${x} z=${z} has bits 6/7 set`);
      row[x] = v;
      if (v > maxTrigger) maxTrigger = v;
    }
    grid.push(row);
  }
  return { grid, maxTrigger };
}

/** .PTH: 65536 bytes next[a][b] (family routing matrix), then width*height x u8 family (0 = impassable), rows in game z order. */
export function parsePth(buf, width, height) {
  if (buf.length !== 65536 + width * height) throw new Error(`.PTH length ${buf.length}, expected ${65536 + width * height}`);
  const families = [];
  let maxFamily = 0;
  for (let z = 0; z < height; z++) {
    const row = new Array(width);
    for (let x = 0; x < width; x++) {
      const v = buf[65536 + z * width + x];
      row[x] = v;
      if (v > maxFamily) maxFamily = v;
    }
    families.push(row);
  }
  // The 256x256 routing matrix stays a byte table (base64): next[a][b] = byte a*256+b. As nested
  // JSON arrays it was more than half of every file.
  return { families, maxFamily, next: buf.subarray(0, 65536).toString('base64') };
}

/** Decode the base64 routing matrix of the JSON back into a lookup: routing(a, b) -> next family (0 = unreachable). */
export function routingTable(nextBase64) {
  const m = Buffer.from(nextBase64, 'base64');
  if (m.length !== 65536) throw new Error(`routing matrix has ${m.length} bytes, expected 65536`);
  return (a, b) => m[a * 256 + b];
}

/** .OVH / .O16: two 96x84 planes (day, night), 8 bpp in .OVH, 16 bpp in .O16. Kept as base64. */
export function parseOverview(buf, bytesPerPixel) {
  const planeBytes = OVERVIEW.width * OVERVIEW.height * bytesPerPixel;
  const expected = planeBytes * OVERVIEW.planes;
  return {
    width: OVERVIEW.width,
    height: OVERVIEW.height,
    bytesPerPixel,
    planes: ['day', 'night'],
    trailingBytes: buf.length - expected,
    data: buf.subarray(0, expected).toString('base64'),
  };
}

// ---------------------------------------------------------------------------------------------
// Text files

const NUM = /^-?\d+$/;

function splitLines(text) {
  return text.split('\n').map((l) => l.replace(/\r$/, ''));
}

/** The game's scenario line reader (mobiles.c 0x41BA3C): skips empty lines and '%' comment lines. */
class ScnReader {
  constructor(text) {
    this.lines = splitLines(text);
    this.pos = 0;
  }
  next(what) {
    while (this.pos < this.lines.length) {
      const l = this.lines[this.pos++];
      if (l.length === 0 || l[0] === '%') continue;
      return l;
    }
    if (what) throw new Error(`.SCN ended before ${what} (line ${this.pos})`);
    return null;
  }
  ints(what) {
    const l = this.next(what);
    return l.trim().split(/\s+/).filter((t) => t.length).map((t) => (NUM.test(t) ? Number(t) : t));
  }
}

const TEAM_COUNT = 8;
const BUILDING_ROWS = 8;
const CITY_SLOT_PAIRS = 5;

/** .SCN: three name lines, five header lines, eight TEAM blocks, then object lines until EOF. */
export function parseScn(text) {
  const rd = new ScnReader(text);
  const terrainFile = rd.next('terrain file').trim();
  const baseName = rd.next('base name').trim();
  const name = rd.next('scenario name').trim();
  const h4 = rd.ints('header line 4');
  const startPhase = Number(rd.next('start phase'));
  const phaseLength = Number(rd.next('phase length'));
  const phaseCounter = Number(rd.next('phase counter'));
  const dawnLength = Number(rd.next('dawn length'));
  const header = {
    scenarioType: h4[0] ?? null, // ignored by the game (mobiles.c reads and drops the line); 0 = multiplayer maps, 1/12 = campaign
    teamCount: h4[1] ?? null,    // ignored by the game; equals the number of TEAM blocks with the active flag set
    startPhase,   // gs+0x53C: 0 day, 1 night
    phaseLength,  // gs+0x534: ticks of one day or night phase
    phaseCounter, // gs+0x530: phase counter at start
    dawnLength,   // gs+0x538: ticks of the dawn / dusk fade
  };

  const teams = [];
  for (let i = 0; i < TEAM_COUNT; i++) {
    const t = rd.ints(`TEAM ${i}`);
    if (t[0] !== 'TEAM' || t[1] !== i) throw new Error(`expected "TEAM ${i}", got "${t.join(' ')}"`);
    const race = Number(rd.next('%Race'));
    const money = Number(rd.next('%Money'));
    const ai = Number(rd.next('%AI'));
    const colour = Number(rd.next('%TeamColour'));
    const depend = rd.ints('%Depend').filter((v) => typeof v === 'number');
    const allies = rd.ints('%TeamAllies').filter((v) => typeof v === 'number');
    const aiSlots = rd.ints('%AISlots').filter((v) => typeof v === 'number');
    const start = rd.ints('city start position');
    const city = rd.ints('city origin');
    const slots = rd.ints('city slots').filter((v) => typeof v === 'number');
    const citySlots = [];
    for (let k = 0; k < CITY_SLOT_PAIRS && 2 * k + 1 < slots.length; k++) citySlots.push({ type: slots[2 * k], count: slots[2 * k + 1] });
    const buildings = [];
    for (let j = 0; j < BUILDING_ROWS; j++) {
      const row = rd.ints(`building row ${j} of team ${i}`).filter((v) => typeof v === 'number');
      buildings.push({ raw: row, weaponLevel: row[2] ?? 0, armourLevel: row[3] ?? 0 });
    }
    teams.push({
      index: i,
      active: t[2] === 1,                       // 3rd number of the TEAM line; written by the editor, not read by the game
      race,                                     // 0 human, 1 gray (campaign only; lobby value in multiplayer)
      money,
      ai,                                       // 0 human, 1..4 AI personality (campaign only)
      colour,                                   // -1 = team index (campaign only)
      depend: stripTerminator(depend),          // DEPEND items already researched (indices < 110), -1 terminated
      allies: allies.slice(0, TEAM_COUNT),      // 8 flags (the game reads the first 8 of the 16 numbers)
      aiSlots: stripTerminator(aiSlots),        // the line under %AISlots; read and ignored by the game
      start: { x: start[0], z: start[1] },     // player+0x38/+0x3C: start position (commander, initial view); (0,0) = same as city
      city: { x: city[0], z: city[1] },        // player+0x30/+0x34: city origin; (0,0) = team has no city
      citySlots,                                // 5 (type,count) pairs, count -1 = unused (all shipped maps)
      buildings,                                // 8 rows, one per building of the race's list: [2] weapon level, [3] armour level
    });
  }

  const objects = [];
  for (;;) {
    const l = rd.next();
    if (l === null) break;
    const v = l.trim().split(/\s+/).filter((t) => t.length && NUM.test(t)).map(Number);
    if (v.length < 5) continue; // sscanf("%d %d %d %d %d %d") with fewer fields; such lines do not occur
    objects.push(decodeObject(v));
  }

  return { terrainFile, baseName, name, header, teams, objects };
}

function stripTerminator(a) {
  const i = a.indexOf(-1);
  return i < 0 ? a : a.slice(0, i);
}

/** One `x z type player a b` line of the .SCN object list (b defaults to 0), decoded as mobiles.c 0x41C603 does. */
export function decodeObject(v) {
  const [x, z, type, player, a, b = 0] = v;
  const o = { x, z, type, typeName: TYPE_NAMES[type] ?? null, player, a, b };
  if (player === -1) {
    o.role = 'spawner'; // renat.c 0x43FFB0: table of at most 25 entries, `a` < 10 (creature generators)
  } else if (type === TYPE_VENT) {
    o.role = 'vent';
    o.rate = player;   // the 4th column is the vent's rate (0 = dormant until a trigger erupts it)
    o.money = a;       // the 5th column is the petra amount
  } else if (type === TYPE_ARTIFACT_SITE) {
    o.role = 'artifactSite';
  } else {
    o.role = 'unit';
  }
  return o;
}

/** .POP (map editor only): four eruption timing values, then `x z 40 rate money` lines of the erupting vents. */
export function parsePop(text) {
  const lines = splitLines(text).map((l) => l.trim()).filter((l) => l.length && l[0] !== '%');
  const timing = [];
  const vents = [];
  for (const l of lines) {
    const v = l.split(/\s+/).filter((t) => NUM.test(t)).map(Number);
    if (v.length === 1 && timing.length < 4 && vents.length === 0) timing.push(v[0]);
    else if (v.length >= 5) vents.push({ x: v[0], z: v[1], type: v[2], rate: v[3], money: v[4] });
  }
  return { timing, vents };
}

const TRO_HEADER = /^(\d+)\s+(norm|trip)\b\s*(.*)$/i;

/** .TRO (renat.c 0x43FD1C): blocks `<id> norm|trip [flag] <condition>` + action lines + `end`. */
export function parseTro(text) {
  const triggers = [];
  let cur = null;
  const lines = splitLines(text);
  for (let i = 0; i < lines.length; i++) {
    const l = lines[i].trim();
    if (!l) continue;
    if (cur === null) {
      const m = TRO_HEADER.exec(l);
      if (!m) throw new Error(`.TRO line ${i + 1}: expected a trigger header, got "${l}"`);
      let rest = m[3].trim();
      let flag = null;
      const f = /^(-?\d+)\s*(.*)$/.exec(rest);
      if (f) { flag = Number(f[1]); rest = f[2]; }
      cur = { id: Number(m[1]), type: m[2].toLowerCase(), flag, condition: rest, actions: [] };
      continue;
    }
    if (l.toLowerCase() === 'end') { triggers.push(cur); cur = null; continue; }
    const parts = l.split(/\s+/);
    const op = parts[0].toLowerCase();
    const args = parts.slice(1).map((t) => (NUM.test(t) ? Number(t) : t));
    // expression arguments such as `setarray 0 (c+45)` may contain spaces: re-join everything after the numbers
    const firstExpr = args.findIndex((t) => typeof t === 'string');
    if (firstExpr >= 0) {
      const expr = parts.slice(1 + firstExpr).join(' ');
      args.splice(firstExpr, args.length - firstExpr, expr);
    }
    cur.actions.push({ op, args });
  }
  if (cur) { cur.unterminated = true; triggers.push(cur); }
  return triggers;
}

// ---------------------------------------------------------------------------------------------
// Scenario = the set of files

const EXTS = ['scn', 'map', 'mtg', 'pth', 'tro', 'pop', 'ovh', 'o16'];

/** Case-insensitive lookup of `<base>.<ext>` in `dir`; DOS-era folders mix upper and lower case. */
export function findScenarioFiles(dir, base) {
  const entries = fs.readdirSync(dir);
  const found = {};
  for (const e of entries) {
    const dot = e.lastIndexOf('.');
    if (dot < 0) continue;
    const stem = e.slice(0, dot);
    const ext = e.slice(dot + 1).toLowerCase();
    if (stem.toLowerCase() === base.toLowerCase() && EXTS.includes(ext) && !(ext in found)) found[ext] = e;
  }
  return found;
}

/**
 * Convert one scenario. `scnPath` is the .SCN file (any case); the sibling files are found by base
 * name. Options: { images: false } to include the .OVH/.O16 caches.
 */
export function convertScenario(scnPath, opts = {}) {
  const dir = path.dirname(scnPath);
  const base = path.basename(scnPath).replace(/\.[^.]*$/, '');
  const files = findScenarioFiles(dir, base);
  if (!files.scn) throw new Error(`no .SCN for ${base} in ${dir}`);
  if (!files.map) throw new Error(`no .MAP for ${base} in ${dir}`);
  const read = (ext) => fs.readFileSync(path.join(dir, files[ext]));

  const scn = parseScn(read('scn').toString('latin1'));
  const map = parseMap(read('map'));
  const mtg = files.mtg ? parseMtg(read('mtg'), map.width, map.height) : null;
  const pth = files.pth ? parsePth(read('pth'), map.width, map.height) : null;
  const triggers = files.tro ? parseTro(read('tro').toString('latin1')) : [];
  const pop = files.pop ? parsePop(read('pop').toString('latin1')) : null;

  const out = {
    format: FORMAT,
    version: FORMAT_VERSION,
    source: { dir: path.resolve(dir), base, files },
    name: scn.name,
    terrainFile: scn.terrainFile,
    terrain: scn.terrainFile.replace(/\.bts$/i, '').toLowerCase(),
    baseName: scn.baseName,
    players: playersFromFileName(files.scn),
    width: map.width,
    height: map.height,
    header: scn.header,
    teams: scn.teams,
    objects: scn.objects,
    tiles: {
      // Tile numbers are the editor's ("original") indices, < remapCount of the terrain's .BTS, which the
      // game remaps to its tile-bank slots on load (docs/DC16_MAP_FILES.md §3.1). 0 = no foreground tile.
      background: map.background,
      foreground: map.foreground,
      // attribute word per cell: bit 9 blocking, bits 0-3 foreground level (cleared without a foreground
      // tile), bits 10-15 terrain class; see the document for the rest
      attributes: map.attributes,
    },
    triggerIds: mtg ? mtg.grid : null,
    // families[z][x]: connected walkable region id, 0 = impassable; next: base64 of the 65536-byte
    // matrix next[a][b] (tools/map2json.js routingTable() decodes it)
    path: pth ? { families: pth.families, maxFamily: pth.maxFamily, next: pth.next } : null,
    script: triggers,
    eruptions: pop,
  };
  if (opts.images) {
    out.overview = {
      ovh: files.ovh ? parseOverview(read('ovh'), 1) : null,
      o16: files.o16 ? parseOverview(read('o16'), 2) : null,
    };
  }
  return out;
}

/** Multiplayer file names carry the player count in the 2nd character (`D8PLAY01.SCN` = 8); null otherwise. */
export function playersFromFileName(file) {
  const c = file[1];
  return c >= '1' && c <= '8' && /^[A-Za-z]\d/.test(file) ? Number(c) : null;
}

/** Compact JSON: objects one key per line, arrays of numbers on one line, grids one row per line. */
export function stringifyCompact(value, indent = 0) {
  const pad = '  '.repeat(indent);
  const pad1 = '  '.repeat(indent + 1);
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    if (value.every((v) => typeof v === 'number' || v === null || typeof v === 'boolean')) return `[${value.join(',')}]`;
    return `[\n${value.map((v) => pad1 + stringifyCompact(v, indent + 1)).join(',\n')}\n${pad}]`;
  }
  if (value !== null && typeof value === 'object') {
    const keys = Object.keys(value);
    if (keys.length === 0) return '{}';
    return `{\n${keys.map((k) => `${pad1}${JSON.stringify(k)}: ${stringifyCompact(value[k], indent + 1)}`).join(',\n')}\n${pad}}`;
  }
  return JSON.stringify(value);
}

// ---------------------------------------------------------------------------------------------
// CLI

function usage() {
  console.error('usage: node tools/map2json.js <scenario.SCN | folder> [...] [--out DIR] [--rooms] [--images] [--pretty]');
  console.error('  --rooms   from a folder, convert only the maps of the default ROOMS (src/config.js)');
  process.exit(2);
}

/** The base names of the server's default rooms (`ROOMS` in src/config.js), upper case, without extension. */
export function defaultRoomBases() {
  return String(DEFAULTS.ROOMS).split(',').map((s) => s.trim().split(':')[0].toUpperCase().replace(/\.SCN$/, '')).filter(Boolean);
}

export function main(argv) {
  const inputs = [];
  let outDir = null;
  let images = false;
  let pretty = false;
  let roomsOnly = false;
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--out') outDir = argv[++i];
    else if (a === '--images') images = true;
    else if (a === '--pretty') pretty = true;
    else if (a === '--rooms') roomsOnly = true;
    else if (a.startsWith('--')) usage();
    else inputs.push(a);
  }
  if (inputs.length === 0) usage();

  const rooms = defaultRoomBases();
  const scnFiles = [];
  for (const inp of inputs) {
    const st = fs.statSync(inp);
    if (st.isDirectory()) {
      for (const e of fs.readdirSync(inp).sort()) {
        if (!/\.scn$/i.test(e)) continue;
        if (roomsOnly && !rooms.includes(e.replace(/\.scn$/i, '').toUpperCase())) continue;
        scnFiles.push(path.join(inp, e));
      }
    } else {
      scnFiles.push(inp);
    }
  }
  if (roomsOnly) {
    const found = scnFiles.map((f) => path.basename(f).replace(/\.scn$/i, '').toUpperCase());
    for (const r of rooms) if (!found.includes(r)) console.error(`warning: room map ${r}.SCN not found in the given folder(s)`);
  }
  if (scnFiles.length === 0) { console.error('no .SCN files found'); process.exit(1); }
  if (scnFiles.length > 1 && !outDir) { console.error('several scenarios: --out DIR is required'); process.exit(1); }

  const index = [];
  let failed = 0;
  for (const scn of scnFiles) {
    let data;
    try {
      data = convertScenario(scn, { images });
    } catch (e) {
      failed++;
      console.error(`${scn}: ${e.message}`);
      continue;
    }
    const text = pretty ? JSON.stringify(data, null, 2) : stringifyCompact(data);
    if (outDir) {
      fs.mkdirSync(outDir, { recursive: true });
      const file = `${data.source.base.toUpperCase()}.json`;
      fs.writeFileSync(path.join(outDir, file), text + '\n');
      index.push({
        file: data.source.files.scn.toUpperCase(), json: file, name: data.name, terrain: data.terrain,
        players: data.players, width: data.width, height: data.height, teams: data.teams.filter((t) => t.active).length,
      });
      console.error(`${file}: ${data.name} (${data.terrain}, ${data.width}x${data.height}, ${text.length} bytes)`);
    } else {
      process.stdout.write(text + '\n');
    }
  }
  if (outDir && index.length) {
    fs.writeFileSync(path.join(outDir, 'index.json'), stringifyCompact({ format: FORMAT, version: FORMAT_VERSION, maps: index }) + '\n');
  }
  if (failed) process.exit(1);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main(process.argv.slice(2));
}
