#!/usr/bin/env python3
"""Assembles the Council Wars (Dark Colony Ultimate) variant of the MP3 music module for patch_music.py.

Developer tool (needs `pip install keystone-engine capstone`); the patched bytes it produces are pasted
into patch_music.py between the `# --- generated by music_asm.py` markers, so the patch tool itself
stays stdlib-only.  Run `python music_asm.py` to regenerate and rewrite that block (and print a
disassembly with `--disasm`).

What the Ultimate module adds to the 22 Sep 2026 player (docs/DC16_DISPLAY_AND_RESOLUTION.md
section 10.31; the seven entry points and the aux-walk hook keep their offsets):

  * a music SOURCE byte in the state block: 0 = "DC" (MUSIC\\TRACK02-05.MP3, the Dark Colony disc),
    1 = "CW" (exp\\music\\track02-05.mp3, the Council Wars disc), 2 = "ALL" (all eight tracks in a
    random order, reshuffled when the eight have played; the first track of a new order is never
    the one that just ended);
  * a track index 0..7 (set = index >> 2, file = TRACK0<2 + (index & 3)>) instead of a track number,
    and two path templates;
  * a private LCG seeded from `rdtsc` (the game's rand() drives the simulation and must not be touched);
  * `opt_tail` and `opt_refresh_tail`: the code behind the MUSIC row of the battlefield options dialog
    (buttons 71 "-" / 72 "+", in_text 73 shows textmsg 20/21/22 = DC/CW/ALL), reached from two
    in-place hooks in interface.c's options handler and its refresh routine;
  * `start_source`: what a source change or the battle start plays first.

State block (the dead CD table of contents, .bss 0x5327D0, 60 bytes):
  +0 device id   +4 track index   +8 volume 0..1000   +12 built file name (24)
  +36 source     +37 shuffle position   +38 shuffle order[8]   +48 LCG state
"""
import re
import sys

import keystone

MOD = 0x451130          # module VA in the Council Wars exe (patch_music.py locates it by pattern)
STATE = 0x5327D0
IAT = 0x480570          # mciSendCommandA
VOL = 0x488E10          # saved music level 0..10
FLAG = 0x489770         # the music layer's "no CD audio" flag (Council Wars)
REFRESH = 0x432C28      # options dialog: refresh the value texts (eax = ctx)
CLOSE_DLG = 0x432584    # options dialog: close (eax = ctx)
TEXTMSG = 0x422718      # textmsg lookup (eax = ip, edx = n) -> string
SETTEXT = 0x423ED4      # set an in_text's text (eax = ip, edx = id, ebx = string)

EXTERNAL = dict(STATE=STATE, IAT=IAT, VOL=VOL, FLAG=FLAG, REFRESH=REFRESH, CLOSE_DLG=CLOSE_DLG,
                TEXTMSG=TEXTMSG, SETTEXT=SETTEXT)

# module layout: name -> offset (fixed, so every reference is a plain number)
LAYOUT = dict(
    cd_open=0x000, play_from_here=0x03C, cd_close=0x088, cd_stop=0x0B8, close_state=0x0E0,
    open_track=0x110, str_mpegvideo=0x1D0, template_dc=0x1DC, setvol_dev=0x200,
    impl_mode=0x240, template_cw=0x2C0, first_idx=0x2E0, cd_tracks=0x338,
    shuffle=0x340, start_source=0x3A0, opt_tail=0x3C0, opt_refresh_tail=0x420, play_dev=0x450, next_idx=0x480, cd_seek_track=0x4E8,
    cd_mode=0x6E0)
MODULE_LEN = 0x751
STRINGS = dict(str_mpegvideo=b'mpegvideo\0', template_dc=b'music\\track0?.mp3\0',
               template_cw=b'exp\\music\\track0?.mp3\0')
DIGIT = dict(template_dc=12, template_cw=16)

# the MUSIC row of the options dialog: widget ids and texts (see music_row() in patch_music.py)
BTN_MINUS, BTN_PLUS, TEXT_ID, MSG_BASE = 71, 72, 73, 20
OBJ_TYPE_OFF = 0x88 + 0x34 * TEXT_ID + 1     # ip->objects[73].type (0x34 bytes per object, from +0x88)
IN_TEXT_TYPE = 4


def sources(s):
    """The functions, as keystone sources; `s` maps symbol -> address."""
    a = lambda name: s[name] if name in s else MOD + LAYOUT[name]
    return {
        'cd_open': f'''
            push edx; push esi
            call {a("close_state"):#x}
            mov eax, [{a("VOL"):#x}]
            imul eax, eax, 100
            mov esi, {a("STATE"):#x}
            mov [esi+8], eax
            rdtsc
            xor eax, edx
            or eax, 1
            mov [esi+48], eax
            mov byte ptr [esi+37], 0
            call {a("first_idx"):#x}
            call {a("open_track"):#x}
            pop esi; pop edx
            ret''',
        'play_from_here': 'xor eax, eax; ret',
        'cd_close': f'jmp {a("close_state"):#x}',
        'cd_stop': f'''
            push ecx; push edx; push esi
            mov esi, {a("STATE"):#x}
            mov eax, [esi]
            test eax, eax
            jz done
            push 0; push 0; push 0x808; push eax
            call dword ptr [{a("IAT"):#x}]
          done:
            xor eax, eax
            pop esi; pop edx; pop ecx
            ret''',
        'close_state': f'''
            push ecx; push edx; push esi
            mov esi, {a("STATE"):#x}
            mov eax, [esi]
            test eax, eax
            jz done
            push 0; push 0; push 0x804; push eax
            call dword ptr [{a("IAT"):#x}]
            xor eax, eax
            mov [esi], eax
          done:
            pop esi; pop edx; pop ecx
            ret''',
        # eax = track index 0..7 -> eax = device id, 0 when the file cannot be opened
        'open_track': f'''
            push ecx; push edx; push esi; push edi; push ebp
            mov ebp, esp
            sub esp, 0x14
            mov edx, eax
            mov esi, {a("template_dc"):#x}
            mov ecx, {DIGIT["template_dc"]}
            test dl, 4
            jz copy
            mov esi, {a("template_cw"):#x}
            mov ecx, {DIGIT["template_cw"]}
          copy:
            mov edi, {a("STATE"):#x}
            add edi, 12
            push edi
            push ecx
            mov ecx, 6
            rep movsd dword ptr es:[edi], dword ptr [esi]
            pop ecx
            pop edi
            mov eax, edx
            and eax, 3
            add al, 0x32
            mov [edi+ecx], al
            mov esi, edi
            sub esi, 12
            mov [esi+4], edx
            xor eax, eax
            mov [ebp-0x14], eax
            mov [ebp-0x10], eax
            mov dword ptr [ebp-0xC], {a("str_mpegvideo"):#x}
            mov [ebp-8], edi
            mov [ebp-4], eax
            lea eax, [ebp-0x14]
            push eax
            push 0x2202
            push 0x803
            push 0
            call dword ptr [{a("IAT"):#x}]
            test eax, eax
            jnz fail
            mov eax, [ebp-0x10]
            mov [esi], eax
            mov ecx, [esi+8]
            call {a("setvol_dev"):#x}
            mov eax, [esi]
            jmp done
          fail:
            xor eax, eax
          done:
            mov esp, ebp
            pop ebp; pop edi; pop esi; pop edx; pop ecx
            ret''',
        # eax = device id: MCI_PLAY, asynchronous, to the end of the file
        'play_dev': f'''
            push ecx; push edx; push ebp
            mov ebp, esp
            sub esp, 0xC
            xor edx, edx
            mov [ebp-0xC], edx
            mov [ebp-8], edx
            mov [ebp-4], edx
            lea edx, [ebp-0xC]
            push edx
            push 0
            push 0x806
            push eax
            call dword ptr [{a("IAT"):#x}]
            mov esp, ebp
            pop ebp; pop edx; pop ecx
            ret''',
        # eax = device id, ecx = volume 0..1000: MCI_SETAUDIO item MCI_DGV_SETAUDIO_VOLUME
        'setvol_dev': f'''
            push ecx; push edx; push ebp
            mov ebp, esp
            sub esp, 0x18
            xor edx, edx
            mov [ebp-0x18], edx
            mov dword ptr [ebp-0x14], 0x4002
            mov [ebp-0x10], ecx
            mov [ebp-0xC], edx
            mov [ebp-8], edx
            mov [ebp-4], edx
            lea edx, [ebp-0x18]
            push edx
            push 0x1800000
            push 0x873
            push eax
            call dword ptr [{a("IAT"):#x}]
            mov esp, ebp
            pop ebp; pop edx; pop ecx
            ret''',
        # cd_mode: MCI_STATUS mode -> 0 playing / 4 error; a stopped file starts the next track
        'impl_mode': f'''
            push ecx; push edx; push esi; push ebp
            mov ebp, esp
            sub esp, 0x10
            mov esi, {a("STATE"):#x}
            mov eax, [esi]
            test eax, eax
            jz err
            xor edx, edx
            mov [ebp-0x10], edx
            mov [ebp-0xC], edx
            mov dword ptr [ebp-8], 4
            mov [ebp-4], edx
            lea edx, [ebp-0x10]
            push edx
            push 0x100
            push 0x814
            push eax
            call dword ptr [{a("IAT"):#x}]
            test eax, eax
            jnz err
            cmp dword ptr [ebp-0xC], 0x20D
            jne ok
            call {a("next_idx"):#x}
            push eax
            call {a("close_state"):#x}
            pop eax
            call {a("open_track"):#x}
            test eax, eax
            jz err
            call {a("play_dev"):#x}
          ok:
            xor eax, eax
          done:
            mov esp, ebp
            pop ebp; pop esi; pop edx; pop ecx
            ret
          err:
            mov eax, 4
            jmp done''',
        # -> eax = the first track index of the current source (ALL: a fresh shuffle)
        'first_idx': f'''
            push esi
            mov esi, {a("STATE"):#x}
            movzx eax, byte ptr [esi+36]
            cmp al, 2
            jae all
            shl eax, 2
            jmp done
          all:
            call {a("shuffle"):#x}
            mov byte ptr [esi+37], 0
            movzx eax, byte ptr [esi+38]
          done:
            pop esi
            ret''',
        # -> eax = the track index after the current one (DC/CW: the set's four tracks in a ring)
        'next_idx': f'''
            push ecx; push esi
            mov esi, {a("STATE"):#x}
            movzx ecx, byte ptr [esi+36]
            cmp cl, 2
            jae all
            mov eax, [esi+4]
            inc eax
            and eax, 3
            shl ecx, 2
            or eax, ecx
            jmp done
          all:
            movzx eax, byte ptr [esi+37]
            inc eax
            cmp al, 8
            jb ok
            call {a("shuffle"):#x}
            xor eax, eax
          ok:
            mov [esi+37], al
            movzx eax, byte ptr [esi+eax+38]
          done:
            pop esi; pop ecx
            ret''',
        'cd_tracks': 'xor eax, eax; ret',
        # esi = STATE: order[0..7] = a random permutation of 0..7 (Fisher-Yates over the LCG);
        # order[0] never equals the track index that just ended
        'shuffle': '''
            push eax; push ecx; push edx; push edi
            xor ecx, ecx
          init:
            mov [esi+ecx+38], cl
            inc ecx
            cmp ecx, 8
            jb init
            mov ecx, 7
          fy:
            mov eax, [esi+48]
            imul eax, eax, 1103515245
            add eax, 12345
            mov [esi+48], eax
            shr eax, 16
            xor edx, edx
            lea edi, [ecx+1]
            div edi
            mov al, [esi+ecx+38]
            mov ah, [esi+edx+38]
            mov [esi+ecx+38], ah
            mov [esi+edx+38], al
            dec ecx
            jnz fy
            mov al, [esi+38]
            cmp al, [esi+4]
            jne done
            mov ah, [esi+39]
            mov [esi+38], ah
            mov [esi+39], al
          done:
            pop edi; pop edx; pop ecx; pop eax
            ret''',
        # close what plays, play the first track of the current source -> eax = device id or 0
        'start_source': f'''
            call {a("close_state"):#x}
            call {a("first_idx"):#x}
            call {a("open_track"):#x}
            test eax, eax
            jz done
            call {a("play_dev"):#x}
            mov eax, [{a("STATE"):#x}]
          done:
            ret''',
        # options handler tail (eax = ctx, edx = widget id, bl = close flag): MUSIC - / + then the
        # original tail (close the dialog when bl is set)
        'opt_tail': f'''
            push ecx; push edx; push esi; push edi
            mov edi, eax
            mov esi, {a("STATE"):#x}
            cmp edx, {BTN_MINUS}
            je minus
            cmp edx, {BTN_PLUS}
            jne close
            movzx eax, byte ptr [esi+36]
            inc eax
            jmp wrap
          minus:
            movzx eax, byte ptr [esi+36]
            add eax, 2
          wrap:
            cmp al, 3
            jb store
            sub al, 3
          store:
            mov [esi+36], al
            cmp dword ptr [{a("FLAG"):#x}], 0
            jne refresh
            cmp dword ptr [esi], 0
            je refresh
            call {a("start_source"):#x}
          refresh:
            mov eax, edi
            call {a("REFRESH"):#x}
          close:
            test bl, bl
            jz done
            mov eax, edi
            call {a("CLOSE_DLG"):#x}
          done:
            pop edi; pop esi; pop edx; pop ecx
            ret''',
        # options refresh tail (ecx = ip, esp restored): in_text 73 = textmsg 20 + source when the
        # script has that widget, then the routine's own epilogue
        'opt_refresh_tail': f'''
            cmp byte ptr [ecx+{OBJ_TYPE_OFF:#x}], {IN_TEXT_TYPE}
            jne epilogue
            mov esi, {a("STATE"):#x}
            movzx edx, byte ptr [esi+36]
            add edx, {MSG_BASE}
            mov eax, ecx
            call {a("TEXTMSG"):#x}
            mov ebx, eax
            mov edx, {TEXT_ID}
            mov eax, ecx
            call {a("SETTEXT"):#x}
          epilogue:
            pop ebp; pop esi; pop edx; pop ecx; pop ebx
            ret''',
        # the music layer's battle start: (eax = device, edx = 2) -> play the source from its first track
        'cd_seek_track': f'''
            push edx
            call {a("start_source"):#x}
            test eax, eax
            jz done
            mov eax, 1
          done:
            pop edx
            ret''',
        'cd_mode': f'jmp {a("impl_mode"):#x}',
    }


def assemble(symbols):
    ks = keystone.Ks(keystone.KS_ARCH_X86, keystone.KS_MODE_32)
    code = bytearray(MODULE_LEN)
    ends = {}
    for name, src in sources(symbols).items():
        off = LAYOUT[name]
        enc, _ = ks.asm(src, MOD + off)
        enc = bytes(enc)
        nxt = min([o for o in LAYOUT.values() if o > off] + [MODULE_LEN])
        if off + len(enc) > nxt:
            raise SystemExit('%s: %d bytes do not fit before +%#x (%d available)' % (name, len(enc), nxt, nxt - off))
        code[off:off + len(enc)] = enc
        ends[name] = off + len(enc)
    for name, s in STRINGS.items():
        off = LAYOUT[name]
        assert s[DIGIT[name]:DIGIT[name] + 1] == b'?' if name in DIGIT else True
        code[off:off + len(s)] = s
    return bytes(code), ends


def _diff_dwords(base_code, moved, delta):
    """Offsets of the dword operands that differ by exactly `delta` between two assemblies."""
    out, i = [], 0
    while i < MODULE_LEN:
        if moved[i] == base_code[i]:
            i += 1
            continue
        for j in range(max(i - 3, 0), i + 1):          # the first differing byte may sit inside the operand
            v0 = int.from_bytes(base_code[j:j + 4], 'little')
            v1 = int.from_bytes(moved[j:j + 4], 'little')
            if (v1 - v0) & 0xFFFFFFFF == delta:
                out.append((j, v0))
                i = j + 4
                break
        else:
            raise SystemExit('unexpected change at +%#x' % i)
    return out


def fixups(base_code):
    """[(offset, kind, add)] by re-assembling with every external symbol moved by a delta."""
    global MOD
    out = []
    delta = 0x00100000
    for kind in EXTERNAL:
        s = dict(EXTERNAL)
        s[kind] = EXTERNAL[kind] + delta
        moved, _ = assemble(s)
        rel = kind in ('REFRESH', 'CLOSE_DLG', 'TEXTMSG', 'SETTEXT')
        for off, v0 in _diff_dwords(base_code, moved, delta):
            out.append((off, 'REL_' + kind, 0) if rel else (off, kind, v0 - EXTERNAL[kind]))
    # module-internal absolute operands (templates, the device-type string): assemble with MOD moved;
    # the rel32 of the four external calls move by -delta then and are skipped as non-matching
    saved = MOD
    MOD = saved + delta
    moved, _ = assemble(dict(EXTERNAL))
    MOD = saved
    i = 0
    while i < MODULE_LEN:
        if moved[i] == base_code[i]:
            i += 1
            continue
        hit = None
        for j in range(max(i - 3, 0), i + 1):
            v0 = int.from_bytes(base_code[j:j + 4], 'little')
            v1 = int.from_bytes(moved[j:j + 4], 'little')
            if (v1 - v0) & 0xFFFFFFFF == delta:
                hit = (j, v0)
                break
        if hit:
            out.append((hit[0], 'MOD', hit[1] - saved))
            i = hit[0] + 4
        else:
            i += 1
    return sorted(out)


def main():
    code, ends = assemble(dict(EXTERNAL))
    fx = fixups(code)
    absolute = [f for f in fx if not f[1].startswith('REL_')]
    print('functions:', ', '.join('%s +%#x..+%#x' % (n, LAYOUT[n], ends[n]) for n in LAYOUT if n in ends))
    print('%d fixups (%d absolute -> .reloc entries, %d relative)' % (len(fx), len(absolute), len(fx) - len(absolute)))
    if '--disasm' in sys.argv:
        import capstone
        md = capstone.Cs(capstone.CS_ARCH_X86, capstone.CS_MODE_32)
        for name in sorted(LAYOUT, key=LAYOUT.get):
            if name in STRINGS:
                print('+%04x %s %r' % (LAYOUT[name], name, STRINGS[name])); continue
            print('--- %s' % name)
            for ins in md.disasm(code[LAYOUT[name]:ends[name]], MOD + LAYOUT[name]):
                print('  +%04x %-14s %s %s' % (ins.address - MOD, ins.bytes.hex(), ins.mnemonic, ins.op_str))
    # write the generated block into patch_music.py
    path = __file__.replace('music_asm.py', 'patch_music.py')
    src = open(path, encoding='utf-8').read()
    start, end = '# --- generated by music_asm.py (do not edit) ---\n', '# --- end generated ---\n'
    a, b = src.index(start), src.index(end)
    block = start
    block += 'CODE_CW = bytes.fromhex(%r)\n' % code.hex()
    block += 'FIXUPS_CW = %r\n' % fx
    block += 'STRINGS_CW = %r\n' % {k: LAYOUT[k] for k in STRINGS}
    src = src[:a] + block + src[b:]
    open(path, 'w', encoding='utf-8', newline='\n').write(src)
    print('patch_music.py updated (%d code bytes)' % sum(1 for x in code if x))


if __name__ == '__main__':
    main()
