#!/usr/bin/env python3
"""patch_online.py - fix `online`: the ONLINE WAR button of Dark Colony Ultimate (29 Sep 2026).

    python patch_online.py verify EXE
    python patch_online.py plan   EXE
    python patch_online.py apply  EXE [--game DIR --width W --height H] [--output OUT]
    python patch_online.py data   DIR --width W --height H        (the two screen scripts, their backgrounds + DEFAULT_SERVER.TXT only)
    python patch_online.py bank   DIR                             (developer: HD_SRC\\KNOBR.SPR = KNOBE + the empty radio box 149 + its grey twin 150)
    python patch_online.py embed  online\\online.dll                (developer: paste a rebuilt module below)

Dark Colony Ultimate only (`Dark Colony Ultimate.exe`, formerly engexp16new.exe); requires fixes
`ozi` (the menu's id chain and the id filter it widened) and `icon` (this fix appends its section
after `.dcicon`), so it is the LAST fix of the Ultimate build.  Docs: DC16_DISPLAY_AND_RESOLUTION.md
10.51, RELAY_SERVER_PLAN.md 20, DC16_NETWORK_PROTOCOL.md 4.4 / 6.9.

What the fix is
---------------
1. A NEW SECTION `.dccode` appended to the file (file offset = the end rounded up to FileAlignment,
   VA = SizeOfImage, code + read + write + execute).  It holds the compiled C module
   online/online.c - the ONLINE WAR screen (the game's own interface engine), DEFAULT_SERVER.TXT,
   the TLS client (Windows Schannel), the relay dialogue (0x50 LIST, 0x51 ROOMS, 0x52 ENTER,
   0x54 ENTERING) and the loopback proxy thread through which the stock lobby/battle code talks to
   the relay.  The module is built by online/build.cmd into a relocatable DLL; `embed` stores its
   single .text section (rdata/data/bss merged), its HIGHLOW relocations and its two exports in
   MODULE below, and plan/apply rebase the absolute operands to the section's VA.  Only the exe's
   LoadLibraryA / GetProcAddress IAT slots are used; the import table is untouched.
2. Three header edits (NumberOfSections + 1, the section header in the zero slack after the section
   table, SizeOfImage) - the resource directory is not touched (that was fix icon's business).
3. Three edits in AUTO: the menu's accepted-id filter `cmp edx,7` at 0x404F9E (5 in the stock exe, 7
   since fix ozi) becomes `cmp edx,9` so the button ids 8 = ONLINE WAR and 9 = REPLAY ONLINE GAME
   (2 Oct 2026) reach the id chain, and the seven NOP bytes at the end of that chain
   (0x405136..0x40513C, left by fix ozi's Dark Colony handlers; the id-7 branch falls through them
   into the loop head 0x40513D) become `jmp online_dispatch` + 2 NOP.  The dispatch (in the section)
   runs `online_war` for id 8, `replay_game` for id 9 and jumps to the loop head for anything else,
   so the fall-through behaves as before.  LOAD GAME (3 Oct 2026, display doc 10.67): the stock load
   routine 0x403AA4 calls its one-folder picker screen `call 0x40388C` at 0x403ABC; the rel32 is
   re-pointed at the module's `load_game_picker`, which lists the saves of save\\, esave\\ and ozisave\\
   together (date, time, name, campaign - the campaign from the folder and the game type in the save's
   header), switches the mode to the chosen save's folder and hands the path back, so the stock code
   loads and resumes it as before.  The menu keeps ONE load button (id 2, last in the left column;
   build_ozi_overlay.py drops LOAD DC GAME 7 and LOAD OZI GAME 4 from the script).

REPLAY ONLINE GAME (2 Oct 2026; plan 21, protocol doc 4.5, display doc 10.65): the second entry point of
the same module.  Its screen REPLAYE is ONLINE with the list narrowed to 40 columns (320 px) and, right
of the scroll bar, a participant pane - eight `checkb` boxes (the lobby's READY boxes, KNOBE cells 9 /
8) with a read-only name field each, under the heading WATCH AS - in a third grey frame; the dialogue
is 0x55 RLIST / 0x56 REPLAYS / 0x57 REPLAY / 0x58 RPLAY / 0x59 REPLAYING and the hand-over after
REPLAYING is the ENTERING one.  The relay formats the rows and the column header.

Data (`apply --game`, `data`): the screen scripts ONLINE, REPLAYE and LOADALLE (the LOAD GAME screen of every
campaign = ONLINE with the title Load Game and the button LOAD, loadall_script; it shares ONLINEBG.GIF).  ONLINE is
the LOAD GAME picker LOADGE with the list
widened from 392 to 448 px (56 columns of MFONTO5, 8 px per column), scroll bar / UP / DOWN 56 px further
right, a read-only header line above the list and a status line below it, the title "Online War",
the buttons ENTER / BACK, a name line and a server line above the status line (the `name=` and the address of
DEFAULT_SERVER.TXT, 3 Oct 2026), the title centred in its panel, the
save-mode widgets and the two animations over the header and status lines removed - written as
INTRF_HD/ONLINE from INTRF_HD/LOADGE at the HD sizes and as INTRFACE/ONLINE from INTRFACE/LOADGE at
640x480 (the module probes for <folder>\\ONLINE, so one exe serves every size), with its background
ONLINEBG.GIF = LOADER.GIF plus grey frames around the header + list, the scroll bar and the two text lines (Pillow);
REPLAYE + REPLAYBG.GIF the same way (replay_script / frame_rects(replay=True): list 40 columns, the pane frame);
and DEFAULT_SERVER.TXT beside the exe (`name=` / `address=` lines since 3 Oct 2026), written when it is missing or
still holds nothing but the shipped address in the first, bare form (a player's own relay address is never
overwritten).  The patcher (Apply-DarkColonyPatches.ps1, Write-OnlineScreen) does the same in PowerShell.
"""
import argparse
import base64
import io
import hashlib
import json
import os
import re
import struct
import sys

SECTION_NAME = b'.dccode'
SECTION_CHARS = 0xE0000020          # code, execute, read, write (the module keeps its state in the section)
IMAGE_BASE = 0x400000
AUTO_VA, AUTO_FILE = 0x401000, 0x400
ULTIMATE_AUTO_RAW = 0x7E400          # the Council Wars build's AUTO raw size (Classic: 0x7E200)
ID_FILTER = 0x404F9E                 # cmp edx, imm8 (83 FA xx): 05 stock, 07 after ozi, 09 after this fix (08 from 29 Sep to 2 Oct 2026)
ID_FILTER_NEW = 9                    # the highest button id: 8 = ONLINE WAR, 9 = REPLAY ONLINE GAME
CHAIN_TAIL = 0x405136                # 7 NOP bytes -> jmp dispatch + 2 NOP
LOOP_HEAD = 0x40513D
DISPATCH_EXPORT, ENTRY_EXPORT, REPLAY_EXPORT = 'online_dispatch', 'online_war', 'replay_game'
# LOAD GAME (3 Oct 2026): the stock LOAD GAME code 0x403AA4 calls the picker screen 0x40388C at 0x403ABC
# (`E8 CB FD FF FF`); the rel32 is re-pointed at the module's `load_game_picker` thunk, which lists the saves
# of every campaign (save / esave / ozisave) and switches the mode to the chosen save's folder
PICKER_CALL, PICKER_TARGET, PICKER_EXPORT = 0x403ABC, 0x40388C, 'load_game_picker'
LIST_WIDTH_OLD, LIST_WIDTH_NEW = 392, 448
SHIFT = LIST_WIDTH_NEW - LIST_WIDTH_OLD
ROW_CHARS = 56                       # 448 px / 8 px per column (MFONTO5: 7 px glyphs on an 8 px advance)
W_STATUS, W_HEADER, W_SERVER = 17, 30, 31   # status line, column header, the server line above the status
W_NAME = 49                                 # the name line above the server line (3 Oct 2026; 32..48 are the replay pane's)
# REPLAY ONLINE GAME (2 Oct 2026): the list is 40 columns (320 px), the scroll bar follows it 72 px further left than
# in the stock LOADGE, and the participant pane sits right of the scroll bar: eight `checkb` rows (KNOBE cells 9 off /
# 8 on, 27x17 as the lobby's READY boxes) 30 px apart from list top + 6, a 13-column read-only name right of each box,
# the heading WATCH AS above them at the header line's height; the pane frame x lx+368 .. lx+518 (150 px, inside the
# 640-wide form at every size: 638 of 640 at 640x480) from the list frame's top to its bottom
RLIST_WIDTH, RROW_CHARS = 320, 40
RSHIFT = RLIST_WIDTH - LIST_WIDTH_OLD        # -72
W_RADIO0, W_RNAME0, W_RPANE = 32, 40, 48
PANE_X0, PANE_X1 = 368, 518                  # the pane frame, relative to the list's x
RADIO_DX, RADIO_DY, RADIO_PITCH = 376, 6, 30 # the boxes: x relative to the list's x, y relative to the list's top
# The boxes come from HD_SRC\KNOBR.SPR (`pictures hd_src/knobr`): KNOBE's 149 cells plus cell 149 = KNOBE's cell 9 without
# the "?" glyph (maintainer, 2 Oct 2026: "client radio buttons must be empty instead of question mark"); the ticked state is
# KNOBE's green cross, cell 8.  The bank is a shipped input of the patcher (HD_SRC, like the console banks), made by `bank`.
RADIO_W, RADIO_H, RADIO_CELLS = 27, 17, (149, 8)
# Slot 0 is the lobby host (its client sets map and options), so it can never be a viewer's seat: its box shows
# cell 150 = the empty box in greys for BOTH states - dimmed, and a click (which the engine toggles and the module
# undoes) changes nothing visible (maintainer, 2 Oct 2026: "slot 0 must contain correct name of ai master as
# before, but it's radio button must be grayed out and unclickable").  The greys are the screen palette's
# (LOADER.GIF: 82 / 65 / 41 / 35 / 23 / 11 at indices 49 / 55 / 62 / 65 / 66 / 67), the reds they replace are
# KNOBE's 80 / 97 / 98 / 99 / 100 / 101 / 201 / 243.
HOST_SLOT = 0
RADIO_CELLS_HOST = (150, 150)
DIM_MAP = {80: 49, 97: 55, 98: 62, 99: 65, 100: 66, 101: 67, 201: 55, 243: 67}
BANK_NAME, BANK_SRC, EMPTY_CELL_FROM = 'knobr', 'KNOBE.SPR', 9
PICTURES_R = b"pictures hd_src/knobr"
RNAME_DX, RNAME_DY, RNAME_CHARS = 407, 3, 13 # the names: x relative to the list's x, y relative to the box, columns
BG_NAME_R = 'replaybg'
# the title: MFONTO2 advances ~16.8 px per character and LOADER.GIF's rounded title panel has ~290 px of flat interior, so
# "Replay Online Game" (18 characters, 302 px) ran onto the panel's rounded ends at every size (maintainer, 3 Oct 2026:
# "'Reply online game' header does not fit in frame") - 13 characters is the longest title that fits
TEXTS_R = {1: b'Online Replay', 2: b'REPLAY'}
TITLE_X_OFF, TITLE_W = -50, 318              # the title panel of LOADER.GIF spans list x - 50 .. + 268 (measured 262..580 at 1024x768)
BG_NAME = 'onlinebg'                         # the screen's background: LOADER.GIF + the grey frame around the two text lines
# the frame (maintainer, 29 Sep 2026: "bottom text area (server name etc.) must be wrapped into a gray frame as
# it is done on the other forms"): a 3-px tube in the console greys of the lobby's boxes - 35, the light edge
# 106/107, 35 - a 2-px black gap and a black interior, corners rounded by one pixel; LOADER.GIF's palette has
# 35 and 106 (indices found by value), 6 px outside the list's columns, from list bottom + 2 to + 46
FRAME_GREYS = (35, 106, 35)
# Three frames (maintainer, same day: "headers section and maps section must be wrapped into a gray frame as
# it is done on the other forms. scroll bar must be wrapped as it is done on the other forms"), all relative to
# the list rect (lx, ly, 448, lh); B = ly + lh = the list's bottom:
#   list frame   x lx-6 .. lx+454, y ly-22 .. B+3       (the column header in_text 30 at ly-16 sits inside)
#   scroll frame x ux-4 .. ux+30,  y ly .. B+2          (ux = lx+460 = the UP/DOWN buttons' x; UP at ly+4, DOWN at B-28)
#   text frame   x lx-6 .. lx+454, y B+8 .. B+68        (name line at B+14, server line at B+30, state line at B+46;
#                                                        B+52 with two lines until 3 Oct 2026; the buttons sit at B+87)
FRAME_MARGIN_X = 6
HEADER_DY, LIST_TOP_DY, LIST_BOTTOM_DY = -16, -22, 3
SCROLL_DX, SCROLL_W = 12, 26
TEXT_TOP_DY, NAME_DY, SERVER_DY, STATUS_DY, TEXT_BOTTOM_DY = 8, 14, 30, 46, 68

DEFAULT_SERVER_TEXT = """/*
 * DEFAULT_SERVER.TXT - the relay server behind ONLINE WAR and REPLAY ONLINE GAME.
 *
 * Dark Colony Ultimate reads this file when you press one of those two buttons in the main
 * menu. It connects to the address below with TLS encryption on port 8889 (the Dark Colony
 * Server relay), shows the rooms or the recorded battles the relay offers and joins the one
 * you pick. Both screens show the name and the address from this file above the connection
 * state.
 *
 * Fields, one per line:
 *   name=<how the screens call this server>          any text; here the relay's project page
 *   address=<host or IP address>[:port]              the port defaults to 8889 (TLS)
 *   plain                                            optional: no encryption, for a relay on
 *                                                    your own network without a certificate
 *                                                    (the plain relay port is 8888)
 * Comments in the C++ style are ignored: "//" at the start of a line or after a space runs to
 * the end of the line (so an address like https://... is kept), or a block like this one.
 * A file holding only an address (the form before 3 Oct 2026) is still understood.
 *
 * Keep one server in the file. CUSTOM NET WAR (the in-game host / CONNECT TO SERVER
 * screens) does not read this file.
 */

name=https://github.com/endotermic/Dark-Colony-Server
address=dark-colony-server.fly.dev
""".replace('\n', '\r\n')

# --- MODULE BEGIN (written by `embed`, do not edit) ---
MODULE = json.loads(
    '{"text":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP////9NQVAgICAgICAgICAgICA'
    'gICAgVEVSUkFJTiAgU0VBVFMgUExBWUVSUyBCT1RTIFNUQVRVUwAAAFdBVENIIEFTAAAAAGludHJmYWNlL29ubGluAABpbnRyZmF'
    'jZS9yZXBsYXkAaW50cmZhY2UvbG9hZGFsbAAAAAAvb25saW4AAFxPTkxJTkUAL3JlcGxheQBcUkVQTEFZRQAAAAAvbG9hZGFsbAA'
    'AAABcTE9BREFMTEUAAABCTU9ubGluZQAAAAAxMjcuMC4wLjEAAACgGAAQqBgAELAYABAuZGNnAAAAAERBVEUgICAgIFRJTUUgICB'
    'OQU1FICAgICAgICAgICAgICAgICAgICAgICAgQ0FNUEFJR04AAAAAc2F2ZQAAAABlc2F2ZQAAAG96aXNhdmUAMDEyMzQ1Njc4OUF'
    'CQ0RFRgAAAABrZXJuZWwzMi5kbGwAAAAAd3MyXzMyLmRsbAAAc2VjdXIzMi5kbGwAQ3JlYXRlRmlsZUEAUmVhZEZpbGUAAAAAQ2x'
    'vc2VIYW5kbGUAR2V0VGlja0NvdW50AAAAAENyZWF0ZVRocmVhZAAAAABTbGVlcAAAAEdldExhc3RFcnJvcgAAAABWaXJ0dWFsQWx'
    'sb2MAAAAAV3JpdGVGaWxlAAAAU2V0RmlsZVBvaW50ZXIAAEZpbmRGaXJzdEZpbGVBAABGaW5kTmV4dEZpbGVBAAAARmluZENsb3N'
    'lAAAARmlsZVRpbWVUb0xvY2FsRmlsZVRpbWUARmlsZVRpbWVUb1N5c3RlbVRpbWUAAAAAV1NBU3RhcnR1cAAAc29ja2V0AABjb25'
    'uZWN0AHNlbmQAAAAAcmVjdgAAAABzZWxlY3QAAGNsb3Nlc29ja2V0AGdldGhvc3RieW5hbWUAAABpbmV0X2FkZHIAAABodG9ucwA'
    'AAG50b2hzAAAAYmluZAAAAABsaXN0ZW4AAGFjY2VwdAAAZ2V0c29ja25hbWUAV1NBR2V0TGFzdEVycm9yAF9fV1NBRkRJc1NldAA'
    'AAABBY3F1aXJlQ3JlZGVudGlhbHNIYW5kbGVBAAAASW5pdGlhbGl6ZVNlY3VyaXR5Q29udGV4dEEAAFF1ZXJ5Q29udGV4dEF0dHJ'
    'pYnV0ZXNBAEVuY3J5cHRNZXNzYWdlAABEZWNyeXB0TWVzc2FnZQAARnJlZUNvbnRleHRCdWZmZXIAAABEZWxldGVTZWN1cml0eUN'
    'vbnRleHQAAABGcmVlQ3JlZGVudGlhbHNIYW5kbGUAAAByZXNvbHZlOiB3czJfMzIuZGxsIG5vdCBsb2FkZWQAAHJlc29sdmU6IHN'
    'lY3VyMzIuZGxsIG5vdCBsb2FkZWQAcmVzb2x2ZTogYSBmdW5jdGlvbiBpcyBtaXNzaW5nIChzZWUgdGhlIFcgdGFibGUgaW4gb25'
    'saW5lLmMpAAAAAE9OTElORS5MT0cAAA0KAABUTFMgZW5jcnlwdCBmYWlsZWQgAFRMUyBkZWNyeXB0IGZhaWxlZCAAVExTIHJlbmV'
    'nb3RpYXRpb24gcmVxdWVzdGVkAE1pY3Jvc29mdCBVbmlmaWVkIFNlY3VyaXR5IFByb3RvY29sIFByb3ZpZGVyAAAAAFRMUyBjcmV'
    'kZW50aWFscyBmYWlsZWQgAFRMUyBoYW5kc2hha2UgdGltZWQgb3V0AGNvbm5lY3Rpb24gY2xvc2VkIGR1cmluZyB0aGUgVExTIGh'
    'hbmRzaGFrZQAAc2VuZCBmYWlsZWQgZHVyaW5nIHRoZSBUTFMgaGFuZHNoYWtlAAAAAFRMUyBoYW5kc2hha2UgZmFpbGVkIAAAACA'
    'oY2VydGlmaWNhdGUgbm90IHRydXN0ZWQpAAAgKGNlcnRpZmljYXRlIG5hbWUgbWlzbWF0Y2gpAAAAACAobm90IGEgVExTIHNlcnZ'
    'lcjsgdHJ5IGBwbGFpbmApAAAAAFRMUyBzdHJlYW0gc2l6ZXMgZmFpbGVkAHBsYWluAAAAbm90bHMAAABERUZBVUxUX1NFUlZFUi5'
    'UWFQAAERFRkFVTFRfU0VSVkVSLlRYVCBub3QgZm91bmQgYmVzaWRlIHRoZSBnYW1lAAAAAG5hbWUAAAAAYWRkcmVzcwBzZXJ2ZXI'
    'AAGhvc3QAAAAAREVGQVVMVF9TRVJWRVIuVFhUIG5hbWVzIG5vIHNlcnZlciBhZGRyZXNzAABQcm90b2NvbCBlcnJvcjogYmFkIGZ'
    'yYW1lIGZyb20gdGhlIHJlbGF5AAAAAFByb3RvY29sIGVycm9yOiBmcmFtZSB0b28gbG9uZwAAbW9uZXkgZml4OiBzaW0gc3RhdGU'
    'gAAAAbW9uZXkgZml4OiBsb2NhbCBwbGF5ZXIgAAAAAG1vbmV5IGZpeDogbW9uZXkgAAAAbW9uZXkgZml4OiBzcGVudCAAAABwcm9'
    '4eTogYWNjZXB0IGZhaWxlZAAAAABwcm94eTogdGhlIGdhbWUgY29ubmVjdGVkAAAAcHJveHk6IGNsb3NpbmcgYm90aCBjb25uZWN'
    '0aW9ucwBXU0FTdGFydHVwIGZhaWxlZAAAAENhbm5vdCByZXNvbHZlIABzb2NrZXQoKSBmYWlsZWQAQ2Fubm90IGNvbm5lY3QgdG8'
    'gAAA6AAAAIChlcnJvciAAAAAAKQAAAHNjcmVlbjogAAAAAHNjcmVlbiBsb2FkZWQAAABOYW1lOiBub25lIChzZWUgREVGQVVMVF9'
    'TRVJWRVIuVFhUKQBTZXJ2ZXI6IG5vbmUgKHNlZSBERUZBVUxUX1NFUlZFUi5UWFQpAAAATmFtZTogAAAtAAAAU2VydmVyOiAAAAA'
    'AQ29ubmVjdGluZyAobm8gZW5jcnlwdGlvbikuLi4AAABDb25uZWN0aW5nIChUTFMpLi4uAGNvbm5lY3RlZCAocGxhaW4pAAAAY29'
    'ubmVjdGVkIChUTFMpAENvbm5lY3RlZC4gUGljayBhIGJhdHRsZSwgdGljayBhIHBsYXllciwgcHJlc3MgUkVQTEFZLgAAQ29ubmV'
    'jdGVkIChUTFMpLiBQaWNrIGEgYmF0dGxlLCB0aWNrIGEgcGxheWVyLCBSRVBMQVkuAABDb25uZWN0ZWQuIFNlbGVjdCBhIHJvb20'
    'gYW5kIHByZXNzIEVOVEVSLgAAAENvbm5lY3RlZCAoVExTKS4gU2VsZWN0IGEgcm9vbSBhbmQgcHJlc3MgRU5URVIuAENvbm5lY3R'
    'pb24gbG9zdC4AAAAAY29ubmVjdDogAAAATm8gcmVjb3JkZWQgYmF0dGxlIG9uIHRoZSBzZXJ2ZXIgeWV0LgAAAHJlcGxheSBsaXN'
    '0OiBlbnRyaWVzIAAAAE5vdCBjb25uZWN0ZWQuIFByZXNzIEJBQ0sgYW5kIHRyeSBhZ2Fpbi4AAAAAU2VsZWN0IGEgcm9vbSBmaXJ'
    'zdC4AAAAARW50ZXJpbmcgcm9vbSAAAC4uLgBTZWxlY3QgYSBiYXR0bGUgZmlyc3QuAABUaWNrIHRoZSBwbGF5ZXIgdG8gd2F0Y2g'
    'gYXMuAAAAAFN0YXJ0aW5nIHRoZSByZXBsYXkgYXMgAFJQTEFZIHJlY29yZGluZyAAAAAAUlBMQVkgc2xvdCAAY2hlY2tiIGV2ZW5'
    '0IGtpbmQgAABjaGVja2IgZXZlbnQgaWQgAAAAAENvdW5jaWwgd2FycwAAAABPemkgbWlzc2lvbnMAAAAAQWNhZGVteQBNdWx0aXB'
    'sYXllcgBVbmtub3duAERhcmsgQ29sb255AC8AAABcKgAALgAAACAAAAAgIAAAc2F2ZXMgZm91bmQgAAAAAFNhdmVzOiAAIChzYXZ'
    'lIAAsIGVzYXZlIAAAAAAsIG96aXNhdmUgAABGaWxlOiAtAFNlbGVjdCBhIHNhdmUgYW5kIHByZXNzIExPQUQuAAAATm8gc2F2ZWQ'
    'gZ2FtZSBmb3VuZC4AAAAARmlsZTogAABTZWxlY3QgYSBzYXZlIGZpcnN0LgAAAABMb2FkaW5nIAAAAABMT0FEIAAAAFZpcnR1YWx'
    'BbGxvYyBmYWlsZWQALS0tIExPQUQgR0FNRSBwcmVzc2VkAAAALS0tIFJFUExBWSBPTkxJTkUgR0FNRSBwcmVzc2VkAAAtLS0gT05'
    'MSU5FIFdBUiBwcmVzc2VkAABjb25maWc6IAAAAABjb25maWc6IG5hbWUgAAAAY29uZmlnOiBob3N0IAAAAGNvbmZpZzogcG9ydCA'
    'AAABjb25maWc6IHBsYWluIAAAYmFjayB0byB0aGUgbWVudQAAAABSRVBMQVlJTkcgc2xvdCAARU5URVJJTkcgc2xvdCAAAGxvb3B'
    'iYWNrIGxpc3RlbmVyIGZhaWxlZAAAAABsb29wYmFjayBwb3J0IAAAY2FsbGluZyB0aGUgZ2FtZSdzIG5ldHdvcmsgZW50cnksIHR'
    'jcCBuZXQgb2JqZWN0IAAAAG5ldHdvcmsgZW50cnkgcmV0dXJuZWQgAAAAAACQ48BqAAAAAA0AAACIAAAACCUAAAgXAAAYAAAAA4A'
    'DgNgkAAAgAAAA+CQAABAAAADNQwAA1EMAAG5EAAB+RAAArUQAALhEAADnRAAA8kQAAAAQAACkFAAAkCUAALAzAAAAAAAAABAAAIQ'
    'HAAAuYnNzAAAAAIQXAAAEAAAALmRhdGEAAACIFwAAOA0AAC5yZGF0YQAAwCQAAEgAAAAucmRhdGEkdm9sdG1kAAAACCUAAIgAAAA'
    'ucmRhdGEkenp6ZGJnAAAAkCUAALAzAAAudGV4dCRtbgAAAABAWQAAkwAAAC5lZGF0YQAAi1QkDItEJARWi/CF0nQTV4t8JBAr+Io'
    'MN4gORoPqAXX1X17Di0wkDIXJdCEPtkQkCFaL8WnAAQEBAVeLfCQMwekC86uLzoPhA/OqX16LRCQEw4tMJAQzwDgBdAdAgDwBAHX'
    '5w4tMJAgz0laLdCQIOBF0HVOLXCQUV4v+Syv5O9N9DIoBQogEOUGAOQB18F9bxgQyAF7Di1QkBFLosv///4tMJBAryAPCUf90JBB'
    'Q6LH///+DxBDDVYvsg+wMi0UMxkX/AIXAdQlqCsZF/jBZ6xhWagtZagpeM9JJ9/aAwjCIVA30hcB18F7/dRCNRfQDwVD/dQjonP/'
    '//4PEDMnDVYvsg+wMi1UMagnGRf4AWYvCweoEg+APioC4GAAQiEQN9EmD+QJ96P91EI1F9GbHRfQweFD/dQjoWv///4PEDMnDikQ'
    'kBDwgdBc8CXQTPA10DzwKdAs8DHQHPAt0AzPAwzPAQMNTVVaLdCQUV4t8JBQr/ooUN4oejUq/jUIggPkZD7boD7bCjVO/D0fojUM'
    'gD7bIgPoZD7bDD0fIiWwkFIvFOsF1DITAdANG68YzwEDrAjPAX15dW8NVi+yDfQwAdA//dRD/dQz/VQiFwHUN6wIzwItNFMcBAAA'
    'AAF3DVY1sJIyhABAAEIHszAAAAIXAdH2DPSAQABAAdHRWVzP/V1dqBFdqAWgAAABAaLwbABD/0Ivwg/7/dFRqAldXVv8VJBAAEGj'
    'GAAAA/3V8jUWoUOgw/v//aMgAAACNRahoyBsAEFDoT/7//4PEGI1FcFdQjUWoUOj6/f//WVCNRahQVv8VIBAAEFb/FQgQABBfXoP'
    'FdMnDUTPAVYstsARIAECDPaAQABAAV4s9gARIAIlEJAgPhe4DAABTVmjMGAAQ/9Vo3BgAEIvw/9Vo6BgAEIvY/9WL6I1EJBBQaPQ'
    'YABBWV+j0/v//owAQABCNRCQgUGgAGQAQVlfo3v7//6MEEAAQjUQkMFBoDBkAEFZX6Mj+//+jCBAAEI1EJEBQaBgZABBWV+iy/v/'
    '/g8RAowwQABCNRCQQUGgoGQAQVlfomf7//6MQEAAQjUQkIFBoOBkAEFZX6IP+//+jFBAAEI1EJDBQaEAZABBWV+ht/v//oxgQABC'
    'NRCRAUGhQGQAQVlfoV/7//4PEQKMcEAAQjUQkEFBoYBkAEFZX6D7+//+jIBAAEI1EJCBQaGwZABBWV+go/v//oyQQABCNRCQwUGh'
    '8GQAQVlfoEv7//6MoEAAQjUQkQFBojBkAEFZX6Pz9//+DxECjLBAAEI1EJBBQaJwZABBWV+jj/f//ozAQABCNRCQgUGioGQAQVlf'
    'ozf3//6M0EAAQjUQkMFBowBkAEFZX6Lf9//+jOBAAEI1EJEBQaNgZABBTV+ih/f//g8RAozwQABCNRCQQUGjkGQAQU1foiP3//6N'
    'AEAAQjUQkIFBo7BkAEFNX6HL9//+jRBAAEI1EJDBQaPQZABBTV+hc/f//o0gQABCNRCRAUGj8GQAQU1foRv3//4PEQKNMEAAQjUQ'
    'kEFBoBBoAEFNX6C39//+jUBAAEI1EJCBQaAwaABBTV+gX/f//o1QQABCNRCQwUGgYGgAQU1foAf3//6NYEAAQjUQkQFBoKBoAEFN'
    'X6Ov8//+DxECjXBAAEI1EJBBQaDQaABBTV+jS/P//o2AQABCNRCQgUGg8GgAQU1fovPz//6NkEAAQjUQkMFBoRBoAEFNX6Kb8//+'
    'jaBAAEI1EJEBQaEwaABBTV+iQ/P//g8RAo2wQABCNRCQQUGhUGgAQU1fod/z//6NwEAAQjUQkIFBoXBoAEFNX6GH8//+jdBAAEI1'
    'EJDBQaGgaABBTV+hL/P//o3gQABCNRCRAUGh4GgAQU1foNfz//4PEQKN8EAAQjUQkEFBoiBoAEFVX6Bz8//+jgBAAEI1EJCBQaKQ'
    'aABBVV+gG/P//o4QQABCNRCQwUGjAGgAQVVfo8Pv//6OIEAAQjUQkQFBo2BoAEFVX6Nr7//+DxECjjBAAEI1EJBBQaOgaABBVV+j'
    'B+///o5AQABCNRCQgUGj4GgAQVVfoq/v//6OUEAAQjUQkMFBoDBsAEFVX6JX7//+jmBAAEI1EJEBQaCQbABBVV+h/+///i3wkUIP'
    'EQKOcEAAQiT2gEAAQhfZ1BDPA6y+F/3Uphdt1C2g8GwAQ6Hj7//9Zhe11C2hcGwAQ6Gn7//9ZaHwbABDoXvv//1mLx15bX11Zw/9'
    '0JAj/dCQI/xV8EAAQw1WNbCSQgezIAAAAjUWoVr7IAAAAVv91eFDor/n//1b/dXyNRahQ6NT5//+NRahQ6BL7//+DxBxeg8VwycN'
    'VjWwkkIHsyAAAAI1FqFa+yAAAAFb/dXhQ6HL5//9W/3V8jUWoUOi4+f//jUWoUOjV+v//g8QcXoPFcMnDU1ZXi0QkEItUJBQz275'
    'IMkIA/9ZfXlvDU1ZXi0QkEL4QMkIA/9ZfXlvDU1ZXi0QkEL5Ee0IA/9ZfXlvDU1ZXi0QkEItUJBSLXCQYi0wkHL64pUIA/9ZfXlv'
    'DU1ZXi0QkEItUJBS+KKhCAP/WX15bw1NWV4tEJBCLVCQUi1wkGL7UPkIA/9ZfXlvDU1ZXi0QkEItUJBSLXCQYvghzQgD/1l9eW8N'
    'TVleLRCQQi1QkFItcJBi+dEVCAP/WX15bw1NWV4tEJBCLVCQUvnxBQgD/1l9eW8NTVleLRCQQM9KLXCQUvvzAQAD/1l9eW8NTVle'
    'LRCQQi1QkFL5swkAA/9ZfXlvDU1ZXvkDzRwD/1l9eW8NTVle+kPJHAP/WX15bw1NWV75A8kcA/9ZfXlvDU1ZXviTgQgD/1l9eW8N'
    'TVleLRCQQi1QkFItcJBiLTCQc/3QkIL4sEkAA/9Yl/wAAAF9eW8NVi+yB7AwBAACLRQy56AMAAJn3+VaJRfgz9mnC6AMAAEZXi30'
    'Iib34/v//ibX0/v//iUX8jUX4UGoAagCNhfT+//9QagD/FVAQABCFwH4SjYX0/v//UFf/FXwQABCFwHUCM/Zfi8ZeycNWi3QkEFe'
    'F9n4ei3wkEGoAVlf/dCQY/xVIEAAQhcB+DivwA/iF9n/mM8BAX17DM8Dr+VaLdCQIV4M+/3QO/zb/FVQQABDHBv////8z/zl+IHQ'
    'NjUYUUP8VmBAAEIl+IDl+HHQNjUYMUP8VnBAAEIl+HF/HRggBAAAAXsOD7DxTVVaLdCRMV4N+CAAPhSgBAACDfgQAdRf/dCRY/3Q'
    'kWP826Fv///+DxAzpDQEAAIt8JFiF/w+O2AAAAItsJFSLXiw7+4tGJA9O3wVEkAAAUwPGVVDoTvb//4tOJI2GRJAAAIlEJDCDxAy'
    'NhkSQAACJTCQcA8HHRCQgBwAAAIlEJDCNgUSQAAADw8dEJCwBAAAAA8aJXCQoiUQkPDPJi0YoiUQkNI1EJByJRCQYjUQkEFFQUY1'
    'GFMdEJEQGAAAAUIlMJFSJTCRYiUwkUIlMJCDHRCQkBAAAAP8VjBAAEIlEJFCFwHUzi0QkNANEJCgDRCQcUI2GRJAAAFD/NuiC/v/'
    '/g8QMhcB0Myv7A+uF/w+PLP///zPAQOskamCBxkTUAABozBsAEFbo4PX//2pg/3QkYFbob/b//4PEGDPAX15dW4PEPMOD7ERTVVZ'
    'Xi3wkWIu3OEgAAIX2D46DAQAAjUc4x0QkKAEAAAAzyYlEJCxqA4lMJBiNVxSJdCQojUQkPFnHQPwAAAAAxwAAAAAAjUAMx0DsAAA'
    'AAIPpAXXkUY1EJCiJTCQciUQkJI1EJBxRUFLHRCQsBAAAAP8VkBAAEIvogf0YAwmAD4QUAQAAgf0XAwkAD4T8AAAAhe10DIH9IQM'
    'JAA+FswAAAGoEM/aNXCQoM8lYiUwkWIlEJBCDewQBdUuLE4XSdEWLj0CQAAC4AEgAACvBO9APT9CNgTxIAABS/3MIA8eJVCQcUOh'
    '49P//i0QkIIPEDAGHQJAAAItEJBCLTCRYx0QkFAEAAACDewQFdQmLSwiLM4lMJFiDwwyD6AGJRCQQdZSF9nQQVlGNRzhQ6DH0//+'
    'DxAzrAjP2ibc4SAAAgf0hAwkAdDGDfCQUAA+Ev/7//zPAQOtHamCNt0TUAABo4BsAEFboXfT//2pgVVbo7/T//4PEGOsfamCNh0T'
    'UAABo9BsAEFDoPPT//4PEDOsHx0cIAQAAAIPI/+sCM8BfXl1bg8REw1NVVot0JBAz7Vc5bggPhcsAAACLXCQgOW4EdCGLvkCQAAC'
    'LhjyQAAA7+H9TVugo/v//WYXAD4ijAAAAf9pT/zbo6vv//1lZhcAPhJcAAABVOW4EdG6LjjhIAAC4AEgAACvBUI1BOAPGUP82/xV'
    'MEAAQhcB+YgGGOEgAAIvd65gr+Dt8JBwPT3wkHAU8SAAAVwPGUP90JCDoIfP//wG+PJAAAIPEDIuOPJAAADuOQJAAAHUMia5AkAA'
    'Aia48kAAAi8frHv90JCD/dCQg/zb/FUwQABCFwH8Kx0YIAQAAAIPI/19eXVvDM8Dr94HsgAAAAFNVVldqODPbjUQkXDP/U0dQiXw'
    'kHOjX8v//i7QkoAAAAI1EJGSDxAzHRCRYBAAAAIlcJHjHhCSIAAAAMABAAI1uDFNVU1NQU2oCaBAcABBT/xWAEAAQi9iF23QlamB'
    'fV4HGRNQAAGhAHAAQVujA8v//V1NW6FPz//+DxBjpggIAADPJiX4ciY44SAAAjX4U6wONbgyDfCQQAI1EJBxqAlqJVCQgiUwkJIl'
    'MJByJTCQox0QkLAEAAACJRCQwdDpRjUQkGFCNRCQwUFdRUVFRaByBAAD/tCS8AAAAUVX/FYQQABCL2MdEJBAAAAAAx0YgAQAAAOk'
    'CAQAAi4Y4SAAAhcB0CIH7GAMJgHVNaJg6AAD/Nugp+v//WVmFwA+EzQEAAIuOOEgAALgASAAAagArwVCNQTgDxlD/Nv8VTBAAEIX'
    'AD46eAQAAAYY4SAAAM8mLhjhIAABqAlpRiUQkRI1uOI1EJESJVCRIiUQkQI1EJBhQjUQkMIlsJFBQUVGNRCRIiUwkZFBRUWgcgQA'
    'A/7QkvAAAAI1GDIlMJHxXUIlMJHyJTCRkiVQkaP8VhBAAEIvYagBZgfsYAwmAD4TT/v//g3wkUAV1K4tMJEyFyXQji744SAAAi9E'
    'r+oPHOAP+igeIRQBFR4PqAXX0iY44SAAA6wrHhjhIAAAAAAAAi3wkJIX/dD2LbCQche10NYsGiUQkGH4fagBVV1D/FUgQABCFwH4'
    '0K+gD+ItEJBiF7X/li3wkJDPtRVf/FZQQABCF7XQehdt0fIH7EgMJAHUejX4UM8npPP7//4t8JCQz7evXamBonBwAEOmLAAAAamB'
    'fV4HGRNQAAGjEHAAQVuiz8P//V1NW6Ebx//+DxBiB+yUDCYB1CFdo3BwAEOsegfsiAwmAdQhXaPgcABDrDoH7JgMJgHVSV2gYHQA'
    'QVuim8P//60GNRiRQagSNRhRQ/xWIEAAQhcB0CWpgaDwdABDrGDPAQIlGBOshamBocBwAEOsHamBoWBwAEI2GRNQAAFDoMfD//4P'
    'EDDPAX15dW4HEgAAAAMNVi+xRU1Yz21NTagNTagFoAAAAgP91CIld/P8VABAAEIvwg8j/O/B0LleLfQyNRfxTUItFEEhQV1b/FQQ'
    'QABCFwHUDiV38Vv8VCBAAEItF/IgcOItF/F9eW8nDM8BQUGoDUGoBaAAAAID/dCQc/xUAEAAQg/j/dQMzwMNQ/xUIEAAQM8BAw4t'
    'UJAQzyTgKdH+APBEvdXKKRBEBPC91KYXJdBIPtkQR/1DoUfD//4PEBIXAdFSAPAoKdE/GBAogQYA8CgB17+tCPCp1PWbHBBEgIIP'
    'BAoA8EQB0NYoECjwqdQeAfAoBL3QPPAp0BMYECiBBgDwKAHXjgDwRAHQSZscEESAgg8EC6wFBgDwRAHWBw4tUJAhVi2wkCFaKCoP'
    'O/1cz/4TJdFOA+TqLxw9FxkeL8IoMOoTJde6F9ng9jXoBM8kD/lOKH4TbdCqNQ9A8CXcja8kKD77Dg8HQA8hHih+E23XnjUH/Pf7'
    '/AAB3B2aJjQABAADGBBYAW2iAAAAAUlXonO7//4PEDF9eXcNVi+xRVot1DIA+AA+ElgAAAFeLfQhTigaIRQz/dQzoT+///4PEBIX'
    'AdApGigaIRQyEwHXnigaEwHRri96IRfz/dfzoK+///4PEBIXAdQpGigaIRfyEwHXngD4AdATGBgBGaFQdABBT6Cnv//9ZWYXAdSB'
    'oXB0AEFPoGO///1lZhcB1DzgHdRVTV+j2/v//WVnrCseHBAEAAAEAAACAPgAPhXH///9bX17Jw1FRU4tcJBAzwGgIAQAAUFPolu3'
    '//2gAEAAA/zWoEAAQaGQdABDooP3//4PEGIXAeR3/dCQYaHgdABD/dCQc6Kjt//8zwIPEDEDpoQEAAFeLPagQABBX6PX9//+APwB'
    'ZD4RHAQAAVVaKB4v3M8mK0ID6CnQSPD11BYXJD0TPR4oHitCEwHXpgD8Ai9d0AUfGAgCKBoTAdDmIRCQQ/3QkEOgk7v//g8QEhcB'
    '0JUaKBohEJBCEwHXl6xiNQv+L0A+2AFDoAu7//4PEBIXAdAfGAgA71nfkgD4AD4TEAAAAhckPhLMAAACNaQEz0usVjUH/i8gPtgB'
    'Q6M7t//+DxASFwHQGiBE7znflikUAhMB0IIhEJBT/dCQU6K3t//+DxASFwHQMRYpFAIhEJBSEwHXkaKgdABBW6LLt//9ZWYXAdBd'
    'ogAAAAI2DgAAAAFVQ6Jrs//+DxAzrS2iwHQAQVuiK7f//WVmFwHUiaLgdABBW6Hnt//9ZWYXAdRFowB0AEFboaO3//1lZhcB0GDP'
    'AxgMAZomDAAEAAFXrAVZT6Lf9//9ZWYA/AA+Fvf7//15dgDsAX3Ua/3QkGGjIHQAQ/3QkHOgn7P//g8QMagJY6yMzwGY5gwABAAB'
    '1FouDBAEAAPfYG8AFuSIAAGaJgwABAAAzwFtZWcNVi+yLVRBTih2sEAAQVos1sBAAEI1CA4vIiUUQwfkIUv91DIgGgOEPisPA4AQ'
    'KyI1GAlCITgHoWev//4tFEP7DUFb/dQiA4w/GRAb/AIgdrBAAEOiS9P//g8QYXltdw1FRU1VWVzP/Rzl8JCB8aYtUJBwz7WoHWYl'
    'MJBAPtgI7wXcOi8iJTCQQhcAPhKEAAAC7vRAAEI13BTt0JCB/OYoEF4hD+4pEFwGIQ/yKRBcCiEP9ikQXA4hD/opEFwSL/ohD/zP'
    'AiXwkFOsHgDw6AHQQRzt8JCB88zPAX15dW1lZwzt8JCB98YP4AnQJR0CD+AN80usqi0QkFIv3ajhZK/A78Q9P8QPCVlBT6Ibq//+'
    'LTCQcg8QMi1QkHEfGBDMAiRytbBIAEEWDwz476Q+MZP///zPAiQ20EAAQQOudi0wkBFYz9oN8JAwCfQQzwF7DigFXPDJ2BWoyX+s'
    'DD7b4M8CJPeATABCJNRQTABBAgDwIAHQIRkA7RCQQfPJqKFg78A9P8I1BAVZQaOQTABDoA+r//4PEDMaG5BMAEAAzwIX/D5TAX17'
    'Dg+wUU1VWV2oHWzlcJCwPjKQAAACLLeATABCF7Q+IlgAAAIs9FBMAEDv9D42IAAAAi3QkKGnXugAAAIoGAxUQEwAQiAKKRgGIQgG'
    'KRgKIQgKKRgOIQgOKRgSIQgQPtk4GD7ZGBWbB4QhmC8iNQghmiUoGM8mDwiCJTCQQiUQkGIlUJBSFycdEJBwoAAAAahBYD0REJBy'
    'LyoN8JBAAiVwkIA9ETCQYiUwkHOsHgDweAHQRQztcJCx88zPAX15dW4PEFMOL8yt0JCA78A9P8ItEJCgDRCQgVlBR6BLp//+LRCQ'
    'og8QMi0wkEEOLVCQUQYPCEYlMJBDGBAYAi3QkKIlUJBSD+QkPjHn///+LRCQYiQS9GBMAEEczwIk9FBMAEDv9D53A65WLTCQIV4P'
    '5AXwpi1QkCA+2AoPoUQ+EnQAAAGoCXyvHdE+D6AF0NyvHdByD6AF0CCvHdCozwF/DjUH/UI1CAVDol/7//+sNjUH/UI1CAVDoH/7'
    '///fYWVkbwPfYX8M7z3zSi0QkEA+2SgFqA4kIWF/DVmp/WI1x/zvwD0/wjUIBVlBoiBIAEOg/6P//g8QMxoaIEgAQADPAhfZ+F4C'
    '4iBIAEAB0B0A7xnzy6wfGgIgSABAAXovHX8ONQf9QjUIBUOjR/P//641RU1VWM9tXiz0MEwAQiVwkEIstCBMAEOtpD7ZdAQ+2RQC'
    'D4w/B4wgL2I1D/T39AwAAD4eWAAAAO/t8Tv90JByNQ/1QjUUCUOju/v//iy0IEwAQi/CLPQwTABAr+1eNBCtQVeid5///i1wkKIP'
    'EGDvziT0MEwAQD0/eiVwkEIP+A3RGg/8CfZLrBItcJBCB/wAgAAB9SGoAuAAgAAArx1CNBC9Q/3QkJOib8///g8QQhcB4QXQkiz0'
    'MEwAQA/iJPQwTABDpSf///2oDWOsqaIAAAABo9B0AEOsOi8PrGmiAAAAAaCAeABBoiBIAEOh35///g8QMg8j/X15dW1nDgz0UFAA'
    'QAA+EmwAAAFaLNdypSgCF9g+EiwAAAFWLrjx9AACD/Qd3flNp3TQOAACDPRwUABAAV4u8M7ALAAB1P1ZoQB4AEMcFHBQAEAEAAAD'
    'ohu3//1VoWB4AEOh77f///7QzrAsAAGh0HgAQ6Grt//9XaIgeABDoX+3//4PEIKEYFAAQO/h9B4vHoxgUABCLzyvIhcl+DSmMM6w'
    'LAACJPRgUABBfW11ew4HsDAEAAFVXM+1VVf81hBcAEP8VcBAAEIv4oYQXABCD+P90EVD/FVQQABDHBYQXABD/////g///dR1onB4'
    'AEOj35////7QkHAEAAOgb7///WVnpkQEAAFZotB4AEOjZ5///oQwTABCLtCQgAQAAWYXAfh5Q/zUIEwAQV+i57v//g8QMhcAPhEM'
    'BAACJLQwTABBTOW4EdDmLhkCQAAA7hjyQAAB/CDmuOEgAAH4jVWgAIAAA/zUQFAAQVuji8f//g8QQhcAPiAMBAAAPj+UAAACLDov'
    'FiXwkHMdEJBgBAAAAOUyEHHQUQIP4AXL0dQyJTCQgx0QkGAIAAAA5LRQUABB0DolsJBDHRCQUoIYBAOsMx0QkEAEAAACJbCQUjUQ'
    'kEFBVVY1EJCRQVf8VUBAAEIvYhdsPiJQAAADoGf7//4XbD4RM////jUQkGFBX/xV8EAAQhcB0K1VoACAAAP81EBQAEFf/FUwQABC'
    'FwH5gUP81EBQAEFboOu7//4PEDIXAdEyNRCQYUP82/xV8EAAQhcAPhPz+//9VaAAgAAD/NRAUABBW6Pnw//+DxBCFwHgeD47d/v/'
    '/UP81EBQAEFfod+3//4PEDIXAD4XF/v//W2jQHgAQ6GPm//9ZV/8VVBAAEFbohe3//1leXzPAXYHEDAEAAMIEAIHspAEAAFeLvCS'
    'sAQAAaKTUAABqAFfocuT//4PEDMcH/////41EJBhQaAICAAD/FTwQABCFwHQkamCNh0TUAABo8B4AEFDoguT//4PEDMdHCAEAAAA'
    'zwOmDAQAAU1WLrCS4AQAAVlX/FVwQABCL8Il0JBCD/v91LFX/FVgQABCFwHRVi0AMhcB0ToM4AHRJagT/MI1EJBhQ6Mzj//+LdCQ'
    'cg8QMagBqAWoCWFD/FUAQABCL2IlcJBCD+/91QGpgjYdE1AAAaBQfABBQ6P3j//+DxAzp1QAAAGpgW1ONt0TUAABoBB8AEFbo4OP'
    '//1NVVugK5P//g8QY6bAAAABqEI1EJBhqAFDoguP//4PEDGoCWGaJRCQUD7eFAAEAAFD/FWAQABBmiUQkFo1EJBRqEFBTiXQkJP8'
    'VRBAAEIXAdHdqYFtTjbdE1AAAaCQfABBW6Hnj//9TVVboo+P//1NoOB8AEFbol+P//w+3hQABAABTUFboqeP//1NoPB8AEFbofOP'
    '//4PEPFP/FXgQABBQVuiM4///U2hIHwAQVuhf4///g8QY/3QkEP8VVBAAEMdHCAEAAADrH4kfg70EAQAAAHUYVVfozu///1lZhcB'
    '1C1foouv//1kzwOsDM8BAXl1bX4HEpAEAAMNVi+yD7BRTVldqEF9qAGoBagJbU4l9/P8VQBAAEIvwiTWEFwAQg/7/D4SEAAAAV41'
    'F7GoAUOhs4v//g8QMZold7DPAx0XwfwAAAWaJRe6NRexXUFb/FWgQABCFwHU+agH/NYQXABD/FWwQABCFwHUsjUX8UI1F7FD/NYQ'
    'XABD/FXQQABCFwHUU/3Xu/xVkEAAQi00IZokBM8BA6xj/NYQXABD/FVQQABDHBYQXABD/////M8BfXlvJw1WL7IPsLMdF1EwjSAC'
    'LRdSJReCDfQgBdQnHRewQGAAQ6xyDfQgCdQnHRfAkGAAQ6wfHRfAAGAAQi0XwiUXsi0XsiUXcg30IAXUJx0XkGBgAEOscg30IAnU'
    'Jx0XoMBgAEOsHx0XoCBgAEItF6IlF5ItF5IlF2MdF+CAUABDHRfQ0FAAQx0X8AAAAAOsHi0X8QIlF/IN9/Ah9IotF+ANF/ItN4AN'
    'N/IoJiAiLRfQDRfyLTeADTfyKCYgI69HHRfwAAAAA6weLRfxAiUX8i0XcA0X8D74AhcB0E4tF+ANF/ItN3ANN/IoJiEgI69mLRfg'
    'DRfzGQAgAx0X8AAAAAOsHi0X8QIlF/ItF2ANF/A++AIXAdBOLRfQDRfyLTdgDTfyKCYhICOvZi0X0A0X8xkAIAMnDa1QkCDQzwIt'
    'MJASAvAqJAAAABA+UwMNWaIAAAAD/dCQQvogSABBW6NDg//9WahH/dCQc6OHn//+DxBhew1Yz9js1SBQAEHUJhfZ0BTPAQOsCM8B'
    'QjUYgUP90JBDo0uf//4PEDEaD/gh81jPAOQVIFAAQXg+cwFBqBf90JAzoy+f//4PEDMOLRCQIU1ZXhcB4FjsFFBMAEH0OafC6AAA'
    'AAzUQEwAQ6wIz9mooxwVIFAAQ/////41+MVuF9nQHgD8Ai8d1BbhKHwAQUFP/dCQY6EXn//+DxAyDxxFDg/swddlfXlv/dCQE6FH'
    '///9Zw4PsaFOLXCRwM8BVVleLSyS9Sh8AEGg8GAAQUYlMJECJRCQsiUQkIIlEJCiJRCQkx0QkNP7///+JRCQ4iUQkMImsJIQAAAC'
    'jtBAAEKMUEwAQxwXgEwAQ/////6LkEwAQowwTABCirBAAEMcFSBQAEP/////oF+f//4u0JJgAAAAzwIX2D5XAUOhV/f//uMwXABC'
    'F9r/cFwAQaDQUABAPRPjoo+///74gFAAQhcCLzg9Ez1FoTB8AEOiF5f//aDQUABDogu///4XAD0T3VlPo6eX//4vwVol0JFzoB+b'
    '//2hYHwAQ6J/g//+LvCS8AAAAuIgXABCF/w9E6FVqHlboKeb//zPtjYQktAAAAFVQVVbo4+X//4PESIX/dBhowBcAEGowVugD5v/'
    '/av9W6Gj+//+DxBQ5rCSEAAAAdDuAvn0KAAAEdRBoaB8AEGoxVujZ5f//g8QMaIwfABBqH1boyeX///+0JJQAAABW6Lr9//+DxBT'
    'pvgEAAGo5jUQkQGi0HwAQUOiG3v//i5wkjAAAALi8HwAQajmNi4AAAACAOQAPRcFQjUQkUFDok97//4PEGIC+fQoAAAR1EI1EJDx'
    'QajFW6GXl//+DxAxqOY1EJEBowB8AEFDoNN7//2o5jUQkTFNQ6Fne//9qOY1EJFhoOB8AEFDoSN7//w+3gwABAABqOVCNRCRoUOh'
    'V3v//jUQkbFBqH1boEuX//zmrBAEAALnsHwAQuMwfABBogAAAAA9EwVBoiBIAEOjS3f//g8RIaIgSABBqEVbo3+T//41EJCxQVug'
    'i5f//U/81pBAAEOje+P//g8QchcAPhJ4AAABqUFiF/2pVWQ9FwTP/iEQkfEc5qwQBAAC5FCAAELgAIAAQiXwkJA9EwVDo6t7//1e'
    'NhCSEAAAAUP81pBAAEOhl8f//g8QQhcB0NYuLBAEAADmsJJAAAAB0GrgkIAAQulwgABCFyQ9EwlBW6Ez8//+L3esduJQgABC6wCA'
    'AEOvkaPAgABBW6DH8//+L34lcJCBZWf8VDBAAEIlEJCjrMqGkEAAQBUTUAABQVugM/P//oaQQABAFRNQAAFBoBCEAEOgP4///g8Q'
    'QM/9Hi9+JXCQYOWwkJA+ENwEAAIXbD4UvAQAA/7QkjAAAAP81pBAAEOhE9P//WVmFwHlKoIgSABCEwHQEPEN1F2iAAAAAaPAgABB'
    'oiBIAEOiF3P//g8QMaIgSABBqEVbokuP///81pBAAEIvfiVwkKOgN5f//g8QQ6c0AAACD+AMPhO0DAAA7xw+F2QEAADmsJJAAAAA'
    'PhLIBAABo5BMAEGoeVuhO4////zUUEwAQaBgTABBVVugI4///oRQTABCDxBzHRCQs/v///4XAdRJoECEAEFboG/v//6EUEwAQWVl'
    'QaDghABDoXuL//1lZOWwkHHVX/xUMEAAQK0QkKD28AgAAckbGRCR8cf8VDBAAEIlEJCiNRCR8V1D/NaQQABDove///4PEDIXAdR9'
    'o8CAAEFbovvr///81pBAAEIvfiVwkJOg75P//g8QMOawkkAAAAHQcVVbohuL//1lZO0QkLHQNUFaJRCQ06Pb6//9ZWY1EJCBQVuj'
    'K4v//WVk7xw+FVAIAAIN8JCAED4TmAgAAg3wkIAUPhW/+//9VVug/4v//WVmF2w+FCwIAADlsJCQPhAECAAA5bCQcD4VK/v//Oaw'
    'kkAAAAA+F6wAAAIXAD4jZAAAAOwW0EAAQD43NAAAAa8A+aIAAAABolCEAEGiIEgAQxkQkHFKKmLgQABCIXCQd6NPa//8PtsO7iBI'
    'AEGiAAAAAUFPoEtv//2iAAAAAaKQhABBT6OHa//9TahFW6MPh//9qAo1EJERQ/zWkEAAQ6Jzu//+DxDzpRgEAAP81tBAAEGhsEgA'
    'QVVboY+H//4PEEOmG/v//g/gCD4V9/v//aIgSABBqEVboeeH//4PEDIlsJBzpav7//2jwIAAQVuhg+f///zWkEAAQi9+JXCQk6N3'
    'i//+DxAzpXP3//2h8IQAQ6RQBAACFwA+I8AAAADsFFBMAEA+N5AAAAIsNSBQAEIXJD4jPAAAAixUQEwAQadi6AAAAa8ERg8AxA8M'
    'DwolEJHyAOAAPhKgAAACKBBNogAAAAGjgIQAQaIgSABDGRCQgWIhEJCGITCQi6LnZ//9ogAAAAP+0JIwAAABoiBIAEOjV2f//aIA'
    'AAABopCEAEGiIEgAQ6MHZ//9oiBIAEGoRVuif4P//oRATABAPtgQDUGj4IQAQ6N7f////NUgUABBoDCIAEOjO3///g8RAjUQkFGo'
    'DUP81pBAAEOhR7f//g8QMhcAPhO7+//+JfCQc6bIAAACLXCQYaMAhABDrHGioIQAQ6xU5rCSEAAAAuFAhABAPRYQkiAAAAFBW6CP'
    '4//9ZWekx/P//OawkkAAAAHR+g/gCdAWD+AN1dItcJCA5bCQwdR1QaBgiABCJfCQ46EXf//9TaCwiABDoOt///4PEEIPD4IP7B3c'
    '1VVbov9///1lZhdt0KIXAeCQ7BRQTABB9HGnIugAAAGvDEQMNEBMAEIB8CDEAdAaJHUgUABBW6MX3//9Zi1wkGOmq+///hcAPhaL'
    '7//9X/xUUEAAQ6Zb7//+L741EJDRQ6B/f///HBCQ8GAAQ/3QkPOjj3///WVmF7XUWOWwkJHQQhdt1DP81pBAAEOjY4P//WV9ei8V'
    'dW4PEaMNVi+yLRQwz0lZqCl739v91EIvKxkUOADPSgMEw9/aNRQyITQ1Q/3UIgMIwiFUM6CPY//+DxAxeXcNTVVaLdCQQM9JXVuj'
    'J1///WYtMJBiL+DgRdCKL3yvZO1QkHH02i0QkII0sC0g76H0SigFCQYgELoA5AHXiO1QkHH0Yi0wkII0EF0k7wX0MQsYEMCBAO1Q'
    'kHHzwjQQXX8YEMABeXVvDi0wkBIoBPAF1BrhAIgAQwzwCdQa4UCIAEMOLSQSD+QN1BrhgIgAQw4P5AnUGuGgiABDDhcm4dCIAELp'
    '8IgAQD0nCw1WL7IPsNFZXM/9XV2oDV2oBaAAAAID/dQiJffz/FQAQABCL8IP+/3RMV41F/FBqLo1FzFBW/xUEEAAQhcB1A4l9/Fb'
    '/FQgQABCDffwuciaAfcxEdSCAfc1DdRqAfc5TdRSAfc9GdQ6BfdIDADQhdQWLRdrrA4PI/19eycOLTCQIi0QkBItRBDlQBHcLdQa'
    'LADsBdwMzwMMzwEDDVYvsVot1EP91DA+2Bv80hVQYABD/dQjoitb///91DGiIIgAQ/3UI6KzW////dQyNRhBQ/3UI6J3W////dQx'
    'oYBgAEP91COiN1v//g8QwXl3DgezwAQAAi4Qk9AEAAFNqQP80hVQYABCNRCR8UOg01v//akCNhCSEAAAAaIwiABBQ6FLW//+DxBi'
    'NhCS0AAAAUI1EJHhQ/xUoEAAQi9iJXCQEg/v/D4RcAQAAVVZXjYQk7AAAAFDo2dX///aEJMQAAAAQi/BZD4UaAQAAg/4ED44RAQA'
    'AjYwk6AAAAAPOaGAYABBR6L3W//9ZWYXAD4TzAAAAjX78g/8gD4/nAAAAgT1wFwAQyAAAAA+N7gAAAGpsjUQkGGoAUOhJ1f//i4Q'
    'kEAIAAIhEJCCNhCT4AAAAV1CNRCQ4UOgH1f//i4Qk7AAAAIuMJPAAAADGRDQ4AIlEJDSNRCQsUI1EJGGJTCQ8ajlQ6Jn+//+NRCR'
    'pUOj0/f//iUQkQIPEKKFwFwAQi+iF7X49ix1MFAAQa8Vsg8OUA9iNQwhQjUQkIFDoQv7//1lZhcB0Eo17bIvzahtNg+tsWfOlhe1'
    '/2otcJBChcBcAEGv9bI10JBRqG1kDPUwUABBAo3AXABCLhCQEAgAA86X/BIV0FwAQjYQkwAAAAFBT/xUsEAAQhcAPhbH+//9T/xU'
    'wEAAQX15dW4HE8AEAAMOD7BhXM/85PXAXABAPjjQBAABTVVYz24stTBQAEI1EJBhqEGoAUAPr6CrU//+DxAyNRCQQUI1FCFD/FTQ'
    'QABCFwHQUjUQkGFCNRCQUUP8VOBAAEIXAdRFqEI1EJBxqAFDo8tP//4PEDI11McYGAA+3RCQeajlQVuj3+///ajlokCIAEFboQNT'
    '//w+3RCQyajlQVujc+///ajlokCIAEFboJdT//w+3RCRIajlQVujB+///ajlolCIAEFboCtT//w+3RCRog8RIajlQVuij+///ajl'
    'oOB8AEFbo7NP//w+3RCQ6ajlQVuiI+///ajlomCIAEFbo0dP//2o5ahqNRRBQVuim+///g8RAajlomCIAEFbos9P//4PEDGo5Vej'
    'y+///WVBW6KDT//+DxAyJNL1QFAAQR4PDbDs9cBcAEA+M1P7//15dW1+DxBjDVscFcBcAEAAAAAAz9lbHBLV0FwAQAAAAAOjZ/P/'
    '/RlmD/gN86F7piv7//4PsSFNVVleLfCRcM9tq/l1oPBgAEItHJFCJRCQgiVwkZMdEJBhKHwAQ6HTa//9qAui/8P//aDQUABDoHOP'
    '//74gFAAQhcC67BcAEIvOD0TKUWhMHwAQ6PnY//9oNBQAEOj24v//hcC47BcAEA9E8FZX6FjZ//+L+FeJfCQ86HbZ///oTv////8'
    '1cBcAEGicIgAQ6PrY//9oaBgAEGoeV+ia2f//oXAXABCNVCRMhcC5UBQAEFAPRMpRU1foStn//4PETI1EJBxqOV5WaKwiABBQ6Ev'
    'S//9W/zVwFwAQjUQkMFDojdL//1aNRCQ4aLQiABBQ6FzS//9W/zV0FwAQjUQkSFDobNL//1aNRCRQaLwiABBQ6DvS//9W/zV4FwA'
    'QjUQkYFDoS9L//4PESI1EJBxWaMgiABBQ6BfS//9W/zV8FwAQjUQkMFDoJ9L//1aNRCQ4aEgfABBQ6PbR//+DxCSAv30KAAAEdRC'
    'NRCQcUGoxV+jI2P//g8QMaNQiABBqH1fouNj//zkdcBcAELn8IgAQuNwiABAPRMFQV+ic8P//g8QUU1foftj//4vwWVk79XReajm'
    'NRCQgi+5oFCMAEFDoXNH//4PEDIX2eCA7NXAXABB9GGvGbAMFTBQAEFCNRCQmajNQ6JH6///rEWo5jUQkIGi8HwAQUOhW0f//g8Q'
    'MjUQkHFBqH1foMdj//4PEDI1EJFxQV+hx2P//WVmD+AF1NIN8JFwED4ThAAAAg3wkXAUPhWv///+F9ngIOzVwFwAQfCdoHCMAEFf'
    'o7e///1lZ6U3///+FwA+FRf///2oB/xUUEAAQ6Tj///+hTBQAEGv2bAPGUP90JGj/dCRo6Pj5//9qOY1EJCxoNCMAEFDojdD//6F'
    'MFAAQg8AQA8ZqOVCNRCQ8UOio0P//ajmNRCREaKQhABBQ6JfQ//+NRCRMUFfode///42EJJQAAABQV+i31///oUwUABCDxECKBAY'
    '8AXUH6PXX///rEDwCdQfo+Nf//+sF6NXX////dCRgaEAjABDoS9b//1kz21lDjUQkFFDoztb//8cEJDwYABD/dCQc6JLX//9ZWV9'
    'eXYvDW4PESMODPYAXABAAdXZqBGgAMAAAaGChAQBqAP8VHBAAEIvIiQ2AFwAQhcl1DmhIIwAQ6DPR//9ZM8DDjYGk1AAAiQ2kEAA'
    'QowgTABCNgaT0AACjEBQAEI2BpBQBAKOwEAAQjYGqGAEAo6gQABCNgaooAQCjEBMAEI2BAE0BAKNMFAAQM8BAw+h00f//hcB0GGh'
    'cIwAQ6NDQ//9Z6GT///+FwA+FKPz//zPAw1WL7IHsfAEAAFMz28dF/P////9WiV346DnR//+FwA+E8AAAAIt1ELmUIwAQhfa4dCM'
    'AEA9EwVDog9D//1mJNRQUABCJHRgUABCJHRwUABDoBf///4XAD4S4AAAAV+iT1v//i10MjUWMamBQjYWE/v//xgX0J1MAAlDHg/A'
    'UAAACAAAAxkWMAOjP4P//i/iDxAyF/3QSjUWMUGisIwAQ6NbU//9ZWetBjYUE////UGi4IwAQ6MHU//+NhYT+//9QaMgjABDosNT'
    '//w+3RYRQaNgjABDo3tT///91iGjoIwAQ6NHU//+DxCBWjUX8UI1FjFBXjYWE/v//UP91COg37v//g8QYX4XAdRFo+CMAEOisz//'
    '/WTPAXlvJw/91/LkcJAAQhfa4DCQAEA9EwVDohNT//41F+FDoJev//4PEDIXAdRhoLCQAEOhzz////zWkEAAQ6JjW//9Z67mLdfg'
    'Pt8ZQaEgkABDoS9T//1lZjUXsUDPAUP81pBAAEGgyPwAQUFD/FRAQABCFwHUm/zWEFwAQ/xVUEAAQ/zWkEAAQxwWEFwAQ/////+h'
    'D1v//6WL///9Q/xUIEAAQM8BmiXXwZolF8sdF9EgYABDoUdX//4vwVmhYJAAQ6NvT//9qAFZTjUXwUP91COhC1f//UGiMJAAQ6MD'
    'T//+hhBcAEIPEJIP4/3QRUP8VVBAAEMcFhBcAEP////8zwEDp+v7//2oA/3QkDP90JAzo1f3//4PEDMNqAf90JAz/dCQM6ML9//+'
    'DxAzDhMl1EVNSUOiO/f//g8QMJf8AAADDaIw4QADDg/8IdBSD/wl1HItV/FBS6L7///+DxAjrDYtV/FBS6Jz///+DxAi5PVFAAP/'
    'hzMzMzMzMzMwAAAAA/////wAAAACQWQAAAQAAAAQAAAAEAAAAaFkAAHhZAACIWQAA8FgAAAtZAADKWAAA3VgAAJtZAACsWQAAvFk'
    'AAMdZAAAAAAEAAgADAG9ubGluZS5kbGwAbG9hZF9nYW1lX3BpY2tlcgBvbmxpbmVfZGlzcGF0Y2gAb25saW5lX3dhcgByZXBsYXl'
    'fZ2FtZQA=","vsize":18899,"text_rva":4096,"image_base":268435456,"relocs":[2132,2136,2140,5801,6003,6'
    '019,6043,6063,6093,6129,6136,6160,6185,6192,6201,6217,6229,6239,6251,6261,6273,6283,6298,6308,6320,6'
    '330,6342,6352,6364,6374,6389,6399,6411,6421,6433,6443,6455,6465,6480,6490,6502,6512,6524,6534,6546,6'
    '556,6571,6581,6593,6603,6615,6625,6637,6647,6662,6672,6684,6694,6706,6716,6728,6738,6753,6763,6775,6'
    '785,6797,6807,6819,6829,6844,6854,6866,6876,6888,6898,6910,6920,6935,6945,6957,6967,6979,6989,7001,7'
    '011,7026,7036,7048,7058,7070,7080,7092,7102,7121,7127,7148,7163,7174,7202,7753,7771,7811,7852,7875,7'
    '893,8130,8202,8355,8589,8622,8768,8866,8974,8981,9002,9121,9213,9324,9436,9466,9507,9527,9558,9574,9'
    '590,9614,9625,9642,9651,9711,9742,9756,9794,9809,10177,10194,10277,10282,10303,10330,10552,10592,106'
    '09,10626,10688,10757,10764,10827,10893,11037,11057,11101,11107,11140,11154,11191,11205,11231,11442,1'
    '1451,11592,11606,11619,11635,11669,11679,11738,11746,11774,11843,11851,11871,11887,11892,11915,11962'
    ',11979,11985,12000,12017,12028,12041,12052,12073,12096,12102,12109,12121,12127,12141,12171,12181,122'
    '00,12223,12263,12334,12381,12416,12432,12439,12450,12476,12496,12522,12545,12558,12631,12648,12688,1'
    '2706,12757,12781,12810,12871,12894,12913,12933,12960,12976,12989,13008,13095,13103,13156,13168,13174'
    ',13192,13198,13211,13228,13234,13240,13283,13298,13307,13332,13347,13356,13375,13382,13594,13626,136'
    '70,13707,13721,13733,13757,13815,13820,13869,13874,13880,13889,13894,13899,13905,13939,13946,13951,1'
    '3964,13977,13987,14021,14038,14082,14124,14140,14180,14198,14262,14292,14342,14347,14361,14374,14400'
    ',14445,14450,14478,14510,14515,14536,14541,14548,14568,14579,14596,14607,14655,14671,14689,14694,147'
    '07,14721,14775,14789,14794,14806,14826,14837,14845,14864,14886,14902,14919,14931,15089,15108,15113,1'
    '5124,15141,15163,15191,15210,15215,15244,15269,15281,15305,15324,15336,15350,15392,15397,15432,15447'
    ',15452,15462,15475,15485,15496,15501,15522,15556,15563,15577,15634,15649,15688,15705,15718,15749,157'
    '73,15804,15995,16005,16019,16030,16038,16043,16081,16106,16120,16222,16238,16269,16306,16330,16358,1'
    '6429,16463,16583,16595,16650,16666,16672,16688,16703,16718,16741,16758,16792,16812,16860,16887,16914'
    ',16944,16971,17001,17036,17046,17067,17081,17124,17144,17161,17171,17178,17189,17199,17211,17244,172'
    '49,17259,17272,17283,17311,17324,17344,17357,17377,17390,17413,17426,17446,17485,17499,17504,17509,1'
    '7550,17569,17580,17606,17681,17688,17717,17727,17757,17768,17797,17833,17875,17902,17929,17952,17960'
    ',17969,17990,17995,18006,18017,18028,18039,18050,18068,18134,18141,18157,18163,18169,18248,18269,182'
    '86,18301,18314,18360,18380,18387,18417,18428,18448,18468,18473,18481,18491,18497,18503,18509,18530,1'
    '8547,18560,18587,18597,18612,18618],"exports":{"load_game_picker":18672,"online_dispatch":18699,"onl'
    'ine_war":18634,"replay_game":18653},"sha":"e4072d827951e649539ae3a5319100097b3864d1321fa34bacf8512af'
    'c6c3502"}'
)
# --- MODULE END ---


def align(v, a):
    return (v + a - 1) // a * a


def va2file(va):
    return va - AUTO_VA + AUTO_FILE


# ------------------------------------------------------------------ PE helpers
class PE:
    def __init__(self, data):
        self.d = data
        self.pe = struct.unpack_from('<I', data, 0x3C)[0]
        assert data[self.pe:self.pe + 4] == b'PE\0\0', 'not a PE file'
        self.nsec_off = self.pe + 6
        self.nsec = struct.unpack_from('<H', data, self.nsec_off)[0]
        self.opt = self.pe + 24
        optsize = struct.unpack_from('<H', data, self.pe + 20)[0]
        assert struct.unpack_from('<H', data, self.opt)[0] == 0x10B, 'PE32 expected'
        self.image_base = struct.unpack_from('<I', data, self.opt + 28)[0]
        self.sect_align, self.file_align = struct.unpack_from('<II', data, self.opt + 32)
        self.size_of_image_off = self.opt + 56
        self.size_of_image = struct.unpack_from('<I', data, self.size_of_image_off)[0]
        self.size_of_headers = struct.unpack_from('<I', data, self.opt + 60)[0]
        self.dirs = self.opt + 96
        self.st = self.opt + optsize
        self.secs = []
        for i in range(self.nsec):
            name, vs, va, rs, ro, _, _, _, _, ch = struct.unpack_from('<8sIIIIIIHHI', data, self.st + 40 * i)
            self.secs.append(dict(name=name.rstrip(b'\0'), vs=vs, va=va, rs=rs, ro=ro, ch=ch))

    def r2o(self, rva):
        for s in self.secs:
            if s['va'] <= rva < s['va'] + max(s['vs'], s['rs']):
                return s['ro'] + rva - s['va']
        raise ValueError(hex(rva))

    def section(self, name):
        return next((s for s in self.secs if s['name'] == name), None)


# ------------------------------------------------------------------ the module (from the DLL)
def read_dll(path):
    """{'text': raw bytes of .text (virtual size), 'vsize', 'relocs': [offset in text], 'exports': {name: offset}, 'sha'}."""
    data = open(path, 'rb').read()
    pe = PE(data)
    text = pe.section(b'.text')
    assert text, 'the DLL has no .text section'
    assert len([s for s in pe.secs if s['name'] not in (b'.text', b'.reloc')]) == 0, \
        'the DLL must have only .text (+ .reloc): build it with build.cmd (/MERGE:.rdata=.text /MERGE:.data=.text /MERGE:.bss=.text)'
    raw = data[text['ro']:text['ro'] + text['rs']]
    body = raw[:text['vs']] if text['vs'] <= len(raw) else raw + b'\0' * (text['vs'] - len(raw))
    # relocations
    relocs = []
    rel = pe.section(b'.reloc')
    if rel:
        pos, end = rel['ro'], rel['ro'] + rel['rs']
        while pos + 8 <= end:
            page, size = struct.unpack_from('<II', data, pos)
            if size == 0:
                break
            for e in struct.unpack_from('<%dH' % ((size - 8) // 2), data, pos + 8):
                typ, off = e >> 12, e & 0xFFF
                if typ == 3:
                    rva = page + off
                    assert text['va'] <= rva < text['va'] + text['vs'] - 3, 'relocation outside .text'
                    relocs.append(rva - text['va'])
                elif typ != 0:
                    raise SystemExit('unexpected relocation type %d' % typ)
            pos += size
    # exports
    exp_rva, exp_size = struct.unpack_from('<II', data, pe.dirs)
    assert exp_rva, 'the DLL exports nothing'
    eo = pe.r2o(exp_rva)
    n_names = struct.unpack_from('<I', data, eo + 24)[0]
    addr_funcs, addr_names, addr_ords = struct.unpack_from('<III', data, eo + 28)
    exports = {}
    for i in range(n_names):
        name_rva = struct.unpack_from('<I', data, pe.r2o(addr_names) + 4 * i)[0]
        ordinal = struct.unpack_from('<H', data, pe.r2o(addr_ords) + 2 * i)[0]
        func_rva = struct.unpack_from('<I', data, pe.r2o(addr_funcs) + 4 * ordinal)[0]
        name = data[pe.r2o(name_rva):].split(b'\0')[0].decode()
        exports[name] = func_rva - text['va']
    for need in (DISPATCH_EXPORT, ENTRY_EXPORT, REPLAY_EXPORT, PICKER_EXPORT):
        assert need in exports, 'export %s missing' % need
    return dict(text=body, vsize=text['vs'], text_rva=text['va'], image_base=pe.image_base,
                relocs=sorted(relocs), exports=exports, sha=hashlib.sha256(body).hexdigest())


def module():
    if MODULE is None:
        raise SystemExit('no module embedded: run online\\build.cmd --embed first')
    m = dict(MODULE)
    m['text'] = base64.b64decode(MODULE['text'])
    assert len(m['text']) == MODULE['vsize'] and hashlib.sha256(m['text']).hexdigest() == MODULE['sha']
    return m


def rebased(m, section_va):
    """The module's bytes with every absolute operand moved from the DLL's .text to `section_va`."""
    body = bytearray(m['text'])
    old_base = m['image_base'] + m['text_rva']
    for off in m['relocs']:
        v = struct.unpack_from('<I', body, off)[0]
        assert old_base <= v < old_base + m['vsize'] + 16, 'relocated operand outside the module: 0x%X' % v
        struct.pack_into('<I', body, off, v - old_base + section_va)
    return bytes(body)


# ------------------------------------------------------------------ the exe
def identify(data):
    pe = PE(data)
    auto = pe.section(b'AUTO')
    if not auto or auto['rs'] != ULTIMATE_AUTO_RAW:
        raise SystemExit('not the Council Wars / Dark Colony Ultimate build (AUTO raw size %s)' % (hex(auto['rs']) if auto else 'none'))
    return pe


def state(data):
    """'stock' (ozi applied, this fix not), 'applied', or a reason string why the fix cannot go in."""
    pe = identify(data)
    imm = data[va2file(ID_FILTER):va2file(ID_FILTER) + 3]
    tail = data[va2file(CHAIN_TAIL):va2file(CHAIN_TAIL) + 7]
    if pe.section(SECTION_NAME):
        return 'applied'
    if imm == bytes.fromhex('83FA05'):
        return 'fix ozi is not applied (the menu id filter still says 5): apply ozi first'
    if imm != bytes.fromhex('83FA07'):
        return 'unexpected menu id filter bytes %s' % imm.hex(' ')
    if tail != b'\x90' * 7:
        return 'the id chain tail at 0x405136 is not the 7 NOP bytes fix ozi leaves: %s' % tail.hex(' ')
    call = data[va2file(PICKER_CALL):va2file(PICKER_CALL) + 5]
    if call != b'\xE8' + struct.pack('<i', PICKER_TARGET - (PICKER_CALL + 5)):
        return 'the LOAD GAME picker call at 0x403ABC is not the stock `call 0x40388C`: %s' % call.hex(' ')
    if not pe.section(b'.dcicon'):
        return 'fix icon is not applied (no .dcicon section): apply icon first, this fix appends its section after it'
    return 'stock'


def plan_edits(data):
    """Return (edits [(offset, old, new, note)], append offset, append bytes, summary)."""
    st = state(data)
    if st != 'stock':
        raise SystemExit('cannot apply: ' + ('already applied (the exe has a %s section)' % SECTION_NAME.decode() if st == 'applied' else st))
    pe = identify(data)
    m = module()
    last_end = max(s['va'] + align(max(s['vs'], s['rs']), pe.sect_align) for s in pe.secs)
    sec_rva = align(max(last_end, pe.size_of_image), pe.sect_align)
    sec_va = IMAGE_BASE + sec_rva
    body = rebased(m, sec_va)
    raw_off = align(len(data), pe.file_align)
    raw_size = align(len(body), pe.file_align)
    append = b'\0' * (raw_off - len(data)) + body + b'\0' * (raw_size - len(body))
    sh_off = pe.st + 40 * pe.nsec
    assert sh_off + 40 <= pe.size_of_headers and data[sh_off:sh_off + 40] == b'\0' * 40, 'no free section header slot'
    new_sh = struct.pack('<8sIIIIIIHHI', SECTION_NAME, m['vsize'], sec_rva, raw_size, raw_off, 0, 0, 0, 0, SECTION_CHARS)
    new_soi = sec_rva + align(m['vsize'], pe.sect_align)
    dispatch = sec_va + m['exports'][DISPATCH_EXPORT]
    jmp = b'\xE9' + struct.pack('<i', dispatch - (CHAIN_TAIL + 5)) + b'\x90\x90'
    replay = sec_va + m['exports'][REPLAY_EXPORT]
    picker = sec_va + m['exports'][PICKER_EXPORT]
    picker_call = b'\xE8' + struct.pack('<i', picker - (PICKER_CALL + 5))
    edits = [
        (pe.nsec_off, data[pe.nsec_off:pe.nsec_off + 2], struct.pack('<H', pe.nsec + 1),
         'PE header: NumberOfSections %d -> %d (the new %s section)' % (pe.nsec, pe.nsec + 1, SECTION_NAME.decode())),
        (pe.size_of_image_off, data[pe.size_of_image_off:pe.size_of_image_off + 4], struct.pack('<I', new_soi),
         'optional header: SizeOfImage 0x%X -> 0x%X' % (pe.size_of_image, new_soi)),
        (sh_off, data[sh_off:sh_off + 40], new_sh,
         'section table: new header %s VA 0x%X size 0x%X, file 0x%X size 0x%X, code + read + write + execute (0x%08X), in the zero slack after the last header'
         % (SECTION_NAME.decode(), sec_rva, m['vsize'], raw_off, raw_size, SECTION_CHARS)),
        (va2file(ID_FILTER) + 2, b'\x07', bytes([ID_FILTER_NEW]),
         'main menu id filter 0x404F9E: cmp edx,7 -> cmp edx,9 (button ids 8 = ONLINE WAR and 9 = REPLAY ONLINE GAME reach the id chain)'),
        (va2file(CHAIN_TAIL), b'\x90' * 7, jmp,
         'end of the id chain 0x405136: 7 NOP -> jmp online_dispatch 0x%X (+2 NOP); id 8 runs online_war, id 9 replay_game 0x%X, other ids continue at 0x40513D as before' % (dispatch, replay)),
        (va2file(PICKER_CALL), b'\xE8' + struct.pack('<i', PICKER_TARGET - (PICKER_CALL + 5)), picker_call,
         'LOAD GAME 0x403AA4: `call 0x40388C` (the stock one-folder picker) at 0x403ABC -> call load_game_picker 0x%X: the saves of every campaign in one list, the mode follows the chosen save\'s folder' % picker),
    ]
    summary = ('new section %s at file 0x%X (VA 0x%X), %d bytes appended: the ONLINE WAR / REPLAY ONLINE GAME / LOAD GAME module (%d bytes of code and data, '
               '%d absolute operands rebased, online_dispatch +0x%X, online_war +0x%X, replay_game +0x%X, load_game_picker +0x%X, module sha256 %s)'
               % (SECTION_NAME.decode(), raw_off, sec_va, len(append), m['vsize'], len(m['relocs']),
                  m['exports'][DISPATCH_EXPORT], m['exports'][ENTRY_EXPORT], m['exports'][REPLAY_EXPORT], m['exports'][PICKER_EXPORT], m['sha'][:16]))
    return edits, len(data), append, summary


def apply_bytes(data, edits, at, append):
    out = bytearray(data)
    for off, old, new, _ in edits:
        assert out[off:off + len(old)] == old
        out[off:off + len(new)] = new
    assert len(out) == at
    return bytes(out) + append


# ------------------------------------------------------------------ data: the screen script
def set_tokens(line, changes):
    """Replace whitespace-separated tokens of a script line by 1-based number, keeping its spacing."""
    toks, n = re.findall(rb'\S+|[ \t]+', line), 0
    for i, tok in enumerate(toks):
        if tok.isspace():
            continue
        n += 1
        if n in changes:
            toks[i] = changes[n]
    return b''.join(toks)


def online_script(src):
    """LOADGE (any size) -> ONLINE: see the module docstring.  Idempotent on its own output."""
    toks = re.search(rb'(?m)^\s*list\s+0\s+\d+\s+(\d+)\s+(\d+)\s+(\d+)\s+(\d+)\s', src)
    if not toks:
        raise SystemExit('LOADGE: no `list 0` line')
    lx, ly, lw, lh = (int(g) for g in toks.groups())
    already = lw == LIST_WIDTH_NEW   # this function's own output: nothing moves again
    if lw not in (LIST_WIDTH_OLD, LIST_WIDTH_NEW):
        raise SystemExit('LOADGE: list width %d, expected %d' % (lw, LIST_WIDTH_OLD))
    shifted = {b'scroll': {1}, b'pushb': {2, 3}, b'gadget': {7, 8}}
    # gadgets 11 (CHOA, the scope animation top right) and 14 (ENCF, the readout under the list) are erased
    # and repainted every frame over the header line's and the status line's right ends, so the ONLINE screen
    # does without them (the background art stays)
    drop = {b'label': {18}, b'pushb': {21}, b'group': {19, 20}, b'textmsg': {4, 5}, b'in_text': {W_HEADER, W_SERVER, W_NAME}, b'gadget': {11, 14}}
    texts = {1: b'Online War', 2: b'ENTER'}
    # below the list: the name line (DEFAULT_SERVER.TXT `name=`; maintainer, 3 Oct 2026: 'add a line with "Name:" above
    # the "Server:" line'), the server line (host:port; maintainer, 29 Sep 2026: "server name must be mentioned as a
    # first line of two right above [the] TLS connection") and the status line
    name_line = b'in_text  %d  0  %d  %d   %d    1  0  -  read_only' % (W_NAME, lx, ly + lh + NAME_DY, ROW_CHARS)
    server_line = b'in_text  %d  0  %d  %d   %d    1  0  -  read_only' % (W_SERVER, lx, ly + lh + SERVER_DY, ROW_CHARS)
    status_line = b'in_text  %d  0  %d  %d   %d    1  0  -  read_only' % (W_STATUS, lx, ly + lh + STATUS_DY, ROW_CHARS)
    header_line = b'in_text  %d  0  %d  %d   %d    1  0  -  read_only' % (W_HEADER, lx, ly + HEADER_DY, ROW_CHARS)
    out = []
    for raw in src.split(b'\n'):
        line, cr = (raw[:-1], b'\r') if raw.endswith(b'\r') else (raw, b'')
        if re.match(rb'\s*background\s+\S+/\S+\s*$', line):               # intrf_hd/loader -> intrf_hd/onlinebg
            out.append(re.sub(rb'(\S+/)\S+\s*$', lambda mm: mm.group(1) + BG_NAME.encode(), line) + cr)
            continue
        m = re.match(rb'\s*(\w+)\s+(\d+)\s', line)
        if m:
            kind, ident = m.group(1), int(m.group(2))
            if ident in drop.get(kind, ()):
                continue
            if kind == b'list' and ident == 0:
                line = set_tokens(line, {6: b'%d' % LIST_WIDTH_NEW})
            elif ident in shifted.get(kind, ()) and not already:
                x = int(re.match(rb'\s*\w+\s+\d+\s+\d+\s+(\d+)', line).group(1))
                line = set_tokens(line, {4: b'%d' % (x + SHIFT)})
            elif kind == b'in_text' and ident == W_STATUS:
                out.append(name_line + cr)
                out.append(server_line + cr)
                out.append(status_line + cr)
                out.append(header_line + cr)
                continue
            elif kind == b'label' and ident == 6:
                # the title: centred in the rounded title panel (the stock label box is left of the panel's centre)
                line = set_tokens(line, {4: b'%d' % (lx + TITLE_X_OFF), 6: b'%d' % TITLE_W})
            elif kind == b'textmsg' and ident in texts:
                num = b'%d' % ident
                line = b'textmsg ' + num + b' ' * (8 - len(num)) + texts[ident]
        out.append(line + cr)
    return b'\n'.join(out)


def replay_script(src):
    """ONLINE (the output of online_script, any size) -> REPLAYE: the list narrowed to 40 columns, the scroll bar,
    UP and DOWN 72 px left of their stock LOADGE places, the participant pane (checkb 32..39, in_text 40..47, the
    heading in_text 48), the title and the WATCH button, the background REPLAYBG.GIF.  Idempotent on its own output."""
    toks = re.search(rb'(?m)^\s*list\s+0\s+\d+\s+(\d+)\s+(\d+)\s+(\d+)\s+(\d+)\s', src)
    if not toks:
        raise SystemExit('ONLINE: no `list 0` line')
    lx, ly, lw, lh = (int(g) for g in toks.groups())
    if lw not in (LIST_WIDTH_NEW, RLIST_WIDTH):
        raise SystemExit('ONLINE: list width %d, expected %d' % (lw, LIST_WIDTH_NEW))
    already = lw == RLIST_WIDTH
    shifted = {b'scroll': {1}, b'pushb': {2, 3}, b'gadget': {7, 8}}
    drop = {b'checkb': set(range(W_RADIO0, W_RADIO0 + 8)), b'in_text': set(range(W_RNAME0, W_RNAME0 + 8)) | {W_RPANE}}
    pane = []
    for k in range(8):
        bx, by = lx + RADIO_DX, ly + RADIO_DY + RADIO_PITCH * k
        cells = RADIO_CELLS_HOST if k == HOST_SLOT else RADIO_CELLS
        pane.append(b'checkb   %d  0  %d  %d   %d   %d  %d   %d   -' % (W_RADIO0 + k, bx, by, RADIO_W, RADIO_H, cells[0], cells[1]))
    for k in range(8):
        pane.append(b'in_text  %d  0  %d  %d   %d    1  0  -  read_only' % (W_RNAME0 + k, lx + RNAME_DX, ly + RADIO_DY + RADIO_PITCH * k + RNAME_DY, RNAME_CHARS))
    pane.append(b'in_text  %d  0  %d  %d   %d    1  0  -  read_only' % (W_RPANE, lx + RADIO_DX, ly + HEADER_DY, RNAME_CHARS + 4))
    out = []
    for raw in src.split(b'\n'):
        line, cr = (raw[:-1], b'\r') if raw.endswith(b'\r') else (raw, b'')
        if re.match(rb'\s*background\s+\S+/\S+\s*$', line):               # .../onlinebg -> .../replaybg
            out.append(re.sub(rb'(\S+/)\S+\s*$', lambda mm: mm.group(1) + BG_NAME_R.encode(), line) + cr)
            continue
        if re.match(rb'\s*pictures\s+\S+\s*$', line):                        # intrface/knobe -> hd_src/knobr (the bank with the empty box)
            out.append(PICTURES_R + cr)
            continue
        m = re.match(rb'\s*(\w+)\s+(\d+)\s', line)
        if m:
            kind, ident = m.group(1), int(m.group(2))
            if ident in drop.get(kind, ()):
                continue                                                      # the pane is re-emitted after the header line
            if kind == b'list' and ident == 0:
                line = set_tokens(line, {6: b'%d' % RLIST_WIDTH})
            elif ident in shifted.get(kind, ()) and not already:
                x = int(re.match(rb'\s*\w+\s+\d+\s+\d+\s+(\d+)', line).group(1))
                line = set_tokens(line, {4: b'%d' % (x - SHIFT + RSHIFT)})
            elif kind == b'in_text' and ident == W_HEADER:
                line = set_tokens(line, {6: b'%d' % RROW_CHARS})
                out.append(line + cr)
                for extra in pane:
                    out.append(extra + cr)
                continue
            elif kind == b'textmsg' and ident in TEXTS_R:
                num = b'%d' % ident
                line = b'textmsg ' + num + b' ' * (8 - len(num)) + TEXTS_R[ident]
        out.append(line + cr)
    return b'\n'.join(out)


TEXTS_L = {1: b'Load Game', 2: b'LOAD'}


def loadall_script(src):
    """ONLINE (the output of online_script, any size) -> LOADALLE, the LOAD GAME screen of every campaign (3 Oct 2026):
    the title "Load Game" and the button LOAD; the list, the header line, the three text lines and the background
    ONLINEBG.GIF are ONLINE's (the module fills them with the save rows, the counts, the chosen file and the state).
    Idempotent on its own output."""
    out = []
    for raw in src.split(b'\n'):
        line, cr = (raw[:-1], b'\r') if raw.endswith(b'\r') else (raw, b'')
        m = re.match(rb'\s*textmsg\s+(\d+)\s', line)
        if m and int(m.group(1)) in TEXTS_L:
            num = m.group(1)
            line = b'textmsg ' + num + b' ' * (8 - len(num)) + TEXTS_L[int(num)]
        out.append(line + cr)
    return b'\n'.join(out)


def knobr_bank(knobe_bytes):
    """KNOBE.SPR -> KNOBR.SPR: the same 149 cells plus cell 149 = cell 9 (the lobby's unticked READY box) with the
    "?" glyph inside the inner square blacked out (rows 5..12, columns 10..17 of the 28x18 cell -> index 254), and
    cell 150 = cell 149 in greys (DIM_MAP) for the host seat's dead box."""
    import io as _io, tempfile
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    import spr
    with tempfile.TemporaryDirectory() as td:
        src = os.path.join(td, 'knobe.spr')
        open(src, 'wb').write(knobe_bytes)
        bank = spr.read_spr(src)
        cells = bank['cells']
        if len(cells) != 149:
            raise SystemExit('KNOBE.SPR: %d cells, expected 149' % len(cells))
        c9 = cells[EMPTY_CELL_FROM]
        w, h = c9['w'], c9['h']
        px = bytearray(c9['px'])
        for y in range(5, 13):
            for x in range(10, 18):
                px[y * w + x] = 254
        cells.append(dict(w=w, h=h, ox=c9['ox'], oy=c9['oy'], px=px))
        cells.append(dict(w=w, h=h, ox=c9['ox'], oy=c9['oy'], px=bytearray(DIM_MAP.get(v, v) for v in px)))
        dst = os.path.join(td, 'knobr.spr')
        spr.write_spr(dst, bank['flags'], cells, bank['palette'])
        return open(dst, 'rb').read()


def write_bank(game, apply):
    """[(path, what)]: HD_SRC\\KNOBR.SPR from INTRFACE\\KNOBE.SPR."""
    src = find_ci(os.path.join(game, 'INTRFACE'), BANK_SRC)
    if not src:
        raise SystemExit('%s: no INTRFACE\\%s' % (game, BANK_SRC))
    data = knobr_bank(open(src, 'rb').read())
    folder = os.path.join(game, 'HD_SRC')
    dst = find_ci(folder, BANK_NAME.upper() + '.SPR') or os.path.join(folder, BANK_NAME.upper() + '.SPR')
    if os.path.isfile(dst) and open(dst, 'rb').read() == data:
        return []
    if apply:
        os.makedirs(folder, exist_ok=True)
        open(dst, 'wb').write(data)
    return [(dst, 'the radio-box bank: KNOBE.SPR + cell 149 = the empty box + cell 150 = the same in greys')]


def grey_index(palette, value):
    """Index of the grey `value` in a 768-byte palette (nearest grey if absent)."""
    best = None
    for i in range(256):
        r, g, b = palette[3 * i:3 * i + 3]
        if r == g == b:
            d = abs(r - value)
            if best is None or d < best[0]:
                best = (d, i)
    assert best is not None, 'no grey in the palette'
    return best[1]


def frame_rects(lx, ly, lh, replay=False):
    """The frames as (x0, y0, x1, y1), x1/y1 exclusive: header + list, scroll bar with its buttons, the two text lines
    - and for the REPLAY screen the participant pane right of the scroll bar, the text frame spanning the whole width."""
    b = ly + lh
    if replay:
        ux = lx + RLIST_WIDTH + SCROLL_DX
        return [
            (lx - FRAME_MARGIN_X, ly + LIST_TOP_DY, lx + RLIST_WIDTH + FRAME_MARGIN_X, b + LIST_BOTTOM_DY),
            (ux - 4, ly, ux + SCROLL_W + 4, b + 2),
            (lx + PANE_X0, ly + LIST_TOP_DY, lx + PANE_X1, b + LIST_BOTTOM_DY),
            (lx - FRAME_MARGIN_X, b + TEXT_TOP_DY, lx + PANE_X1, b + TEXT_BOTTOM_DY),
        ]
    ux = lx + LIST_WIDTH_NEW + SCROLL_DX
    return [
        (lx - FRAME_MARGIN_X, ly + LIST_TOP_DY, lx + LIST_WIDTH_NEW + FRAME_MARGIN_X, b + LIST_BOTTOM_DY),
        (ux - 4, ly, ux + SCROLL_W + 4, b + 2),
        (lx - FRAME_MARGIN_X, b + TEXT_TOP_DY, lx + LIST_WIDTH_NEW + FRAME_MARGIN_X, b + TEXT_BOTTOM_DY),
    ]


def draw_frame(pixels, width, x0, y0, x1, y1, greys, black):
    """Paint the frame into a row-major index buffer (a bytearray of width*height): tube, gap, interior."""
    def put(x, y, v):
        pixels[y * width + x] = v
    for y in range(y0, y1):
        for x in range(x0, x1):
            d = min(x - x0, x1 - 1 - x, y - y0, y1 - 1 - y)      # distance from the outer edge
            corner = (x in (x0, x1 - 1)) and (y in (y0, y1 - 1))
            if corner:
                continue                                          # one pixel off each corner
            put(x, y, greys[d] if d < len(greys) else black)


def online_background(gif_bytes, lx, ly, lh, replay=False):
    """LOADER.GIF (any size) -> the ONLINE (or, with `replay`, the REPLAYE) screen's background: the same picture with the grey frames."""
    try:
        from PIL import Image
    except ImportError:
        raise SystemExit('Pillow is needed to draw the frame into the background (pip install pillow)')
    with Image.open(io.BytesIO(gif_bytes)) as im:
        if im.mode != 'P':
            raise SystemExit('LOADER.GIF is not a palette picture')
        palette = im.getpalette()[:768]
        w, h = im.size
        pixels = bytearray(im.tobytes())
    greys = [grey_index(palette, g) for g in FRAME_GREYS]
    black = grey_index(palette, 0)
    for rect in frame_rects(lx, ly, lh, replay):
        draw_frame(pixels, w, *rect, greys, black)
    out = Image.frombytes('P', (w, h), bytes(pixels))
    out.putpalette(palette)
    buf = io.BytesIO()
    out.save(buf, format='GIF', version='GIF87a', interlace=False, optimize=False)   # as pad_background.py / the patcher's codec
    return buf.getvalue()


def find_ci(folder, name):
    if not os.path.isdir(folder):
        return None
    for f in os.listdir(folder):
        if f.lower() == name.lower():
            return os.path.join(folder, f)
    return None


def bare_shipped_config(data):
    """True for a DEFAULT_SERVER.TXT of the first form (before 3 Oct 2026) that still names only the shipped relay:
    comments off (the module's rule: `//` counts at a line start or after white space), exactly one token,
    `dark-colony-server.fly.dev`.  Such a file is upgraded to the `name=` / `address=` form; anything else is the
    player's own setting and stays.  The patcher's Write-OnlineScreen applies the same test."""
    text = data.decode('latin1')
    text = re.sub(r'(?s)/\*.*?\*/', ' ', text)
    text = re.sub(r'(?m)(^|\s)//.*$', r'\1', text)
    return [t.lower() for t in text.split()] == ['dark-colony-server.fly.dev']


def write_data(game, width, height, apply):
    """[(path, what)] written (or planned): the ONLINE script for the size and DEFAULT_SERVER.TXT if missing."""
    done = []
    hd = not (width == 640 and height == 480)
    import hdfolder
    folder = os.path.join(game, hdfolder.hd_folder(width, height) if hd else 'INTRFACE')   # the size's own folder (2 Oct 2026)
    src = find_ci(folder, 'LOADGE')
    if not src:
        raise SystemExit('%s: no LOADGE to derive the ONLINE screen from' % folder)
    data = online_script(open(src, 'rb').read())
    dst = find_ci(folder, 'ONLINE') or os.path.join(folder, 'ONLINE')
    if not (os.path.isfile(dst) and open(dst, 'rb').read() == data):
        done.append((dst, 'the ONLINE WAR screen (%dx%d) from %s' % (width, height, os.path.basename(src))))
        if apply:
            open(dst, 'wb').write(data)
    loader = find_ci(folder, 'LOADER.GIF')
    if not loader:
        raise SystemExit('%s: no LOADER.GIF to derive the ONLINE background from' % folder)
    m = re.search(rb'(?m)^\s*list\s+0\s+\d+\s+(\d+)\s+(\d+)\s+\d+\s+(\d+)\s', data)
    bg = online_background(open(loader, 'rb').read(), int(m.group(1)), int(m.group(2)), int(m.group(3)))
    bgdst = find_ci(folder, BG_NAME.upper() + '.GIF') or os.path.join(folder, BG_NAME.upper() + '.GIF')
    if not (os.path.isfile(bgdst) and open(bgdst, 'rb').read() == bg):
        done.append((bgdst, 'the ONLINE WAR background: LOADER.GIF with the grey frame around the text lines'))
        if apply:
            open(bgdst, 'wb').write(bg)
    # REPLAY ONLINE GAME (2 Oct 2026): the second screen, derived from the ONLINE script just written
    rdata = replay_script(data)
    rdst = find_ci(folder, 'REPLAYE') or os.path.join(folder, 'REPLAYE')
    if not (os.path.isfile(rdst) and open(rdst, 'rb').read() == rdata):
        done.append((rdst, 'the REPLAY ONLINE GAME screen (%dx%d) from the ONLINE script' % (width, height)))
        if apply:
            open(rdst, 'wb').write(rdata)
    rbg = online_background(open(loader, 'rb').read(), int(m.group(1)), int(m.group(2)), int(m.group(3)), replay=True)
    rbgdst = find_ci(folder, BG_NAME_R.upper() + '.GIF') or os.path.join(folder, BG_NAME_R.upper() + '.GIF')
    if not (os.path.isfile(rbgdst) and open(rbgdst, 'rb').read() == rbg):
        done.append((rbgdst, 'the REPLAY ONLINE GAME background: LOADER.GIF with the frames around the list, the scroll bar, the participant pane and the text lines'))
        if apply:
            open(rbgdst, 'wb').write(rbg)
    # LOAD GAME (3 Oct 2026): the third screen, ONLINE with the title and the button changed; it shares ONLINEBG.GIF
    ldata = loadall_script(data)
    ldst = find_ci(folder, 'LOADALLE') or os.path.join(folder, 'LOADALLE')
    if not (os.path.isfile(ldst) and open(ldst, 'rb').read() == ldata):
        done.append((ldst, 'the LOAD GAME screen (%dx%d) from the ONLINE script: every campaign\'s saves in one list' % (width, height)))
        if apply:
            open(ldst, 'wb').write(ldata)
    cfg = find_ci(game, 'DEFAULT_SERVER.TXT')
    if not cfg or bare_shipped_config(open(cfg, 'rb').read()):
        what = 'DEFAULT_SERVER.TXT (name= / address= dark-colony-server.fly.dev; written when missing or still the bare shipped address)'
        cfg = cfg or os.path.join(game, 'DEFAULT_SERVER.TXT')
        done.append((cfg, what))
        if apply:
            open(cfg, 'wb').write(DEFAULT_SERVER_TEXT.encode('latin1'))
    return done


# ------------------------------------------------------------------ CLI
def print_plan(edits, at, append, summary):
    for off, old, new, note in edits:
        print('  %s  file 0x%x %d bytes: %s -> %s' % (note, off, len(old), old.hex(' '), new.hex(' ')))
    print('  append at file 0x%x %d bytes sha256 %s: %s' % (at, len(append), hashlib.sha256(append).hexdigest(), summary))


def embed(dll_path, self_path):
    m = read_dll(dll_path)
    rec = dict(text=base64.b64encode(m['text']).decode(), vsize=m['vsize'], text_rva=m['text_rva'], image_base=m['image_base'],
               relocs=m['relocs'], exports=m['exports'], sha=m['sha'])
    src = open(self_path, encoding='utf-8').read()
    begin, end = '# --- MODULE BEGIN (written by `embed`, do not edit) ---\n', '# --- MODULE END ---'
    a, b = src.index(begin) + len(begin), src.index(end)
    text = json.dumps(rec, indent=None, separators=(',', ':'))
    # wrap the base64 so that the file stays readable
    lines = ['MODULE = json.loads(']
    while text:
        lines.append('    %r' % text[:100])
        text = text[100:]
    lines.append(')')
    src = src[:a] + '\n'.join(lines) + '\n' + src[b:]
    open(self_path, 'w', encoding='utf-8', newline='\n').write(src)
    print('embedded %s: %d bytes of code and data, %d relocations, exports %s, sha256 %s'
          % (os.path.basename(dll_path), m['vsize'], len(m['relocs']), ', '.join('%s +0x%X' % kv for kv in sorted(m['exports'].items())), m['sha'][:16]))


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('cmd', choices=['verify', 'plan', 'apply', 'data', 'embed', 'bank'])
    ap.add_argument('target', help='the exe (verify/plan/apply), the game folder (data) or the DLL (embed)')
    ap.add_argument('--game', help='apply: also write the ONLINE and REPLAYE screens and DEFAULT_SERVER.TXT into this game folder')
    ap.add_argument('--width', type=int, default=1024)
    ap.add_argument('--height', type=int, default=768)
    ap.add_argument('--output', help='apply: write here instead of in place (no backup then)')
    a = ap.parse_args()
    if a.cmd == 'embed':
        return embed(a.target, os.path.abspath(__file__))
    if a.cmd == 'data':
        for path, what in write_data(a.target, a.width, a.height, True):
            print('  written %s: %s' % (path, what))
        return None
    if a.cmd == 'bank':
        for path, what in write_bank(a.target, True) or [(None, 'HD_SRC\\KNOBR.SPR is up to date')]:
            print('  %s%s' % (('written %s: ' % path) if path else '', what))
        return None
    data = open(a.target, 'rb').read()
    if a.cmd == 'verify':
        st = state(data)
        if st == 'applied':
            pe = PE(data)
            s = pe.section(SECTION_NAME)
            body = data[s['ro']:s['ro'] + s['vs']]
            m = module() if MODULE else None
            same = m and rebased(m, IMAGE_BASE + s['va']) == body
            print('%s: online APPLIED (%s at VA 0x%X, %d bytes%s)' % (a.target, SECTION_NAME.decode(), IMAGE_BASE + s['va'], s['vs'],
                                                                       '; = the embedded module' if same else '; a DIFFERENT module build' if m else ''))
        else:
            print('%s: online NOT applied (%s)' % (a.target, st))
        return None
    edits, at, append, summary = plan_edits(data)
    print('%s: Dark Colony Ultimate, fix online: %d header/code edits + %d bytes appended' % (a.target, len(edits), len(append)))
    print_plan(edits, at, append, summary)
    if a.cmd == 'plan':
        if a.game:
            for path, what in write_data(a.game, a.width, a.height, False):
                print('  would write %s: %s' % (path, what))
        return None
    out = apply_bytes(data, edits, at, append)
    if a.output:
        open(a.output, 'wb').write(out)
        print('written %s (%d bytes)' % (a.output, len(out)))
    else:
        bak = a.target + '.online.bak'
        if not os.path.exists(bak):
            open(bak, 'wb').write(data)
        open(a.target, 'wb').write(out)
        print('written %s (%d bytes); backup %s' % (a.target, len(out), bak))
    if a.game:
        for path, what in write_data(a.game, a.width, a.height, True):
            print('  written %s: %s' % (path, what))
    return None


if __name__ == '__main__':
    main()
