"""The patcher's resources: the project's own files that the installer copies into the game folder (5 Oct 2026,
maintainer: "put all patcher's resources and scripts (except installer.cmd and PATCH_HOWTO.TXT) into a separate
folder", then "don't delete files from where they was! You must use 'patcher' directory as a source from where you
take resources and copy to the places where they must reside").

Since 5 Oct 2026 the Dark-Colony repository has a folder `patcher/`:

    patcher/Apply-DarkColonyPatches.ps1     the patcher (generated by gen_apply_script.py)
    patcher/game/<rel>                      a COPY of every resource of the game folder, copied in by the installer
    patcher/editor/<rel>                    the same for the map editor's folder

The game folders keep every file where it always was (the repository stays playable as checked out); `patcher/` is the
SOURCE the installer copies from, so that the installer package for ModDB - INSTALL.CMD + PATCH_HOWTO.TXT + patcher/,
nothing of Strategic Simulations' in it - can rebuild a game folder from the player's own discs (tools/discs.py) or
complete an existing install.  On a repository checkout the copy finds identical files and changes nothing.

A tracked file of the two game folders is one of

    disc       on one of the two CDs (tools/disc_manifest.json says where) - the stock game
    output     written by the patcher (the HD_<height>P interface sets, the patched exes)
    local      repository-only (the MP3 soundtrack, the 1998 dc16.exe, InstallShield logs) - never in the package
    derived    the installer writes it by a rule (the 1998 typo fix of human09.tro)
    resource   the project's own work, or the ozi_ns pack's: ALSO in patcher/game | patcher/editor

    python tools/resources.py list                        every resource with its root
    python tools/resources.py sync GAME_REPO              copy the resources from the game folders into patcher/game |
                                                          patcher/editor (after a dev tool changed one; identical files
                                                          are skipped) - the two sides must stay equal
    python tools/resources.py check GAME_REPO             report every resource whose two copies differ or that is
                                                          missing on one side (exit 1 if any)
"""
import json, os, shutil, sys

TOOLS = os.path.dirname(os.path.abspath(__file__))
MANIFEST = os.path.join(TOOLS, 'disc_manifest.json')
GAME_FOLDER = 'DC - Council wars'
EDITOR_FOLDER = 'Dark Colony - Map editor'
FOLDER_OF = {'game': GAME_FOLDER, 'editor': EDITOR_FOLDER}
PATCHER_DIR = 'patcher'


def manifest():
    return json.load(open(MANIFEST, encoding='utf-8'))


def resources(m=None):
    """[(root, rel)] of every resource, from the manifest's classification."""
    m = m or manifest()
    return [tuple(x.split(':', 1)) for x in m['resources']]


def resource_root(game_repo, root):
    return os.path.join(game_repo, PATCHER_DIR, root)


def cmd_list(a):
    for root, rel in resources():
        print('%-6s %s' % (root, rel))


def cmd_sync(a):
    """Dev tools (build_ozi_overlay.py, hud_console.py, paint_intro.py, tracer.py, make_dc_icon.py ...) write into
    the game folder; this copies the resource files among their outputs into patcher/<root>."""
    n = 0
    for root, rel in resources():
        src = os.path.join(a.game_repo, FOLDER_OF[root], rel)
        dst = os.path.join(resource_root(a.game_repo, root), rel)
        if not os.path.exists(src):
            print('MISSING in the game folder:', root, rel)
            continue
        if os.path.exists(dst) and open(src, 'rb').read() == open(dst, 'rb').read():
            continue
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copy2(src, dst); n += 1
        print('synced', root, rel)
    print('%d file(s) copied into %s' % (n, PATCHER_DIR))


def cmd_check(a):
    bad = 0
    for root, rel in resources():
        src = os.path.join(a.game_repo, FOLDER_OF[root], rel)
        dst = os.path.join(resource_root(a.game_repo, root), rel)
        if not os.path.exists(src) or not os.path.exists(dst):
            print('MISSING', 'game folder' if not os.path.exists(src) else PATCHER_DIR, root, rel); bad += 1
        elif open(src, 'rb').read() != open(dst, 'rb').read():
            print('DIFFERS', root, rel); bad += 1
    print('%d resource(s), %d problem(s)' % (len(resources()), bad))
    return 1 if bad else 0


def main(argv=None):
    import argparse
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest='cmd', required=True)
    sub.add_parser('list')
    p = sub.add_parser('sync'); p.add_argument('game_repo')
    p = sub.add_parser('check'); p.add_argument('game_repo')
    a = ap.parse_args(argv)
    return {'list': cmd_list, 'sync': cmd_sync, 'check': cmd_check}[a.cmd](a) or 0


if __name__ == '__main__':
    sys.exit(main())
